'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UPS_RegWebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RegisterBinding", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class RegisterMgrAcctService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private uPSSecurityValueField As UPSSecurity
        
        Private ProcessRegisterOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessManageAccountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.UPS_RegWebReference_RegisterMgrAcctService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property UPSSecurityValue() As UPSSecurity
            Get
                Return Me.uPSSecurityValueField
            End Get
            Set
                Me.uPSSecurityValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ProcessRegisterCompleted As ProcessRegisterCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessManageAccountCompleted As ProcessManageAccountCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute(" http://www.ups.com/XMLSchema/XOLTWS/RegistrationBinding/v1.0", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ProcessRegister(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")> ByVal RegisterRequest As RegisterRequest) As <System.Xml.Serialization.XmlElementAttribute("RegisterResponse", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")> RegisterResponse
            Dim results() As Object = Me.Invoke("ProcessRegister", New Object() {RegisterRequest})
            Return CType(results(0),RegisterResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessRegisterAsync(ByVal RegisterRequest As RegisterRequest)
            Me.ProcessRegisterAsync(RegisterRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessRegisterAsync(ByVal RegisterRequest As RegisterRequest, ByVal userState As Object)
            If (Me.ProcessRegisterOperationCompleted Is Nothing) Then
                Me.ProcessRegisterOperationCompleted = AddressOf Me.OnProcessRegisterOperationCompleted
            End If
            Me.InvokeAsync("ProcessRegister", New Object() {RegisterRequest}, Me.ProcessRegisterOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessRegisterOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessRegisterCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessRegisterCompleted(Me, New ProcessRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/RegistrationBinding/v1.0", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ProcessManageAccount(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")> ByVal ManageAccountRequest As ManageAccountRequest) As <System.Xml.Serialization.XmlElementAttribute("ManageAccountResponse", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")> ManageAccountResponse
            Dim results() As Object = Me.Invoke("ProcessManageAccount", New Object() {ManageAccountRequest})
            Return CType(results(0),ManageAccountResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessManageAccountAsync(ByVal ManageAccountRequest As ManageAccountRequest)
            Me.ProcessManageAccountAsync(ManageAccountRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessManageAccountAsync(ByVal ManageAccountRequest As ManageAccountRequest, ByVal userState As Object)
            If (Me.ProcessManageAccountOperationCompleted Is Nothing) Then
                Me.ProcessManageAccountOperationCompleted = AddressOf Me.OnProcessManageAccountOperationCompleted
            End If
            Me.InvokeAsync("ProcessManageAccount", New Object() {ManageAccountRequest}, Me.ProcessManageAccountOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessManageAccountOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessManageAccountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessManageAccountCompleted(Me, New ProcessManageAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable:=false)>  _
    Partial Public Class UPSSecurity
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameTokenField As UPSSecurityUsernameToken
        
        Private serviceAccessTokenField As UPSSecurityServiceAccessToken
        
        '''<remarks/>
        Public Property UsernameToken() As UPSSecurityUsernameToken
            Get
                Return Me.usernameTokenField
            End Get
            Set
                Me.usernameTokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceAccessToken() As UPSSecurityServiceAccessToken
            Get
                Return Me.serviceAccessTokenField
            End Get
            Set
                Me.serviceAccessTokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>  _
    Partial Public Class UPSSecurityUsernameToken
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class RegCodeDescriptionType
        
        Private codeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
    Partial Public Class CodeDescriptionType
        
        Private codeField As String
        
        Private descriptionField As String
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
    Partial Public Class ResponseType
        
        Private responseStatusField As CodeDescriptionType
        
        Private alertField() As CodeDescriptionType
        
        Private transactionReferenceField As TransactionReferenceType
        
        '''<remarks/>
        Public Property ResponseStatus() As CodeDescriptionType
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Alert")>  _
        Public Property Alert() As CodeDescriptionType()
            Get
                Return Me.alertField
            End Get
            Set
                Me.alertField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
    Partial Public Class TransactionReferenceType
        
        Private customerContextField As String
        
        Private transactionIdentifierField As String
        
        '''<remarks/>
        Public Property CustomerContext() As String
            Get
                Return Me.customerContextField
            End Get
            Set
                Me.customerContextField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionIdentifier() As String
            Get
                Return Me.transactionIdentifierField
            End Get
            Set
                Me.transactionIdentifierField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class InvoiceInfoType
        
        Private invoiceNumberField As String
        
        Private invoiceDateField As String
        
        Private currencyCodeField As String
        
        Private invoiceAmountField As String
        
        Private controlIDField As String
        
        '''<remarks/>
        Public Property InvoiceNumber() As String
            Get
                Return Me.invoiceNumberField
            End Get
            Set
                Me.invoiceNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceDate() As String
            Get
                Return Me.invoiceDateField
            End Get
            Set
                Me.invoiceDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrencyCode() As String
            Get
                Return Me.currencyCodeField
            End Get
            Set
                Me.currencyCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceAmount() As String
            Get
                Return Me.invoiceAmountField
            End Get
            Set
                Me.invoiceAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ControlID() As String
            Get
                Return Me.controlIDField
            End Get
            Set
                Me.controlIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class ShipperAccountType
        
        Private accountNameField As String
        
        Private accountNumberField As String
        
        Private postalCodeField As String
        
        Private countryCodeField As String
        
        Private invoiceInfoField As InvoiceInfoType
        
        '''<remarks/>
        Public Property AccountName() As String
            Get
                Return Me.accountNameField
            End Get
            Set
                Me.accountNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InvoiceInfo() As InvoiceInfoType
            Get
                Return Me.invoiceInfoField
            End Get
            Set
                Me.invoiceInfoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class AddressType
        
        Private addressLineField() As String
        
        Private cityField As String
        
        Private stateProvinceCodeField As String
        
        Private postalCodeField As String
        
        Private countryCodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressLine")>  _
        Public Property AddressLine() As String()
            Get
                Return Me.addressLineField
            End Get
            Set
                Me.addressLineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StateProvinceCode() As String
            Get
                Return Me.stateProvinceCodeField
            End Get
            Set
                Me.stateProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
    Partial Public Class RequestType
        
        Private requestOptionField() As String
        
        Private transactionReferenceField As TransactionReferenceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("RequestOption")>  _
        Public Property RequestOption() As String()
            Get
                Return Me.requestOptionField
            End Get
            Set
                Me.requestOptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>  _
    Partial Public Class UPSSecurityServiceAccessToken
        
        Private accessLicenseNumberField As String
        
        '''<remarks/>
        Public Property AccessLicenseNumber() As String
            Get
                Return Me.accessLicenseNumberField
            End Get
            Set
                Me.accessLicenseNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class RegisterRequest
        
        Private requestField As RequestType
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private companyNameField As String
        
        Private customerNameField As String
        
        Private titleField As String
        
        Private addressField As AddressType
        
        Private phoneNumberField As String
        
        Private phoneExtensionField As String
        
        Private emailAddressField As String
        
        Private endUserIPAddressField As String
        
        Private notificationCodeField As String
        
        Private shipperAccountField As ShipperAccountType
        
        Private deviceIdentityField As String
        
        Private suggestUsernameIndicatorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
        Public Property Request() As RequestType
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CustomerName() As String
            Get
                Return Me.customerNameField
            End Get
            Set
                Me.customerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As AddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneExtension() As String
            Get
                Return Me.phoneExtensionField
            End Get
            Set
                Me.phoneExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmailAddress() As String
            Get
                Return Me.emailAddressField
            End Get
            Set
                Me.emailAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndUserIPAddress() As String
            Get
                Return Me.endUserIPAddressField
            End Get
            Set
                Me.endUserIPAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NotificationCode() As String
            Get
                Return Me.notificationCodeField
            End Get
            Set
                Me.notificationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipperAccount() As ShipperAccountType
            Get
                Return Me.shipperAccountField
            End Get
            Set
                Me.shipperAccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeviceIdentity() As String
            Get
                Return Me.deviceIdentityField
            End Get
            Set
                Me.deviceIdentityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuggestUsernameIndicator() As String
            Get
                Return Me.suggestUsernameIndicatorField
            End Get
            Set
                Me.suggestUsernameIndicatorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class RegisterResponse
        
        Private responseField As ResponseType
        
        Private suggestedUsernameField As String
        
        Private shipperAccountStatusField() As RegCodeDescriptionType
        
        Private disclaimerField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
        Public Property Response() As ResponseType
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuggestedUsername() As String
            Get
                Return Me.suggestedUsernameField
            End Get
            Set
                Me.suggestedUsernameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShipperAccountStatus")>  _
        Public Property ShipperAccountStatus() As RegCodeDescriptionType()
            Get
                Return Me.shipperAccountStatusField
            End Get
            Set
                Me.shipperAccountStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Disclaimer")>  _
        Public Property Disclaimer() As String()
            Get
                Return Me.disclaimerField
            End Get
            Set
                Me.disclaimerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class ManageAccountRequest
        
        Private requestField As RequestType
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private shipperAccountField As ShipperAccountType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
        Public Property Request() As RequestType
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipperAccount() As ShipperAccountType
            Get
                Return Me.shipperAccountField
            End Get
            Set
                Me.shipperAccountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Registration/v2.0")>  _
    Partial Public Class ManageAccountResponse
        
        Private responseField As ResponseType
        
        Private shipperAccountStatusField() As RegCodeDescriptionType
        
        Private disclaimerField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>  _
        Public Property Response() As ResponseType
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ShipperAccountStatus")>  _
        Public Property ShipperAccountStatus() As RegCodeDescriptionType()
            Get
                Return Me.shipperAccountStatusField
            End Get
            Set
                Me.shipperAccountStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Disclaimer")>  _
        Public Property Disclaimer() As String()
            Get
                Return Me.disclaimerField
            End Get
            Set
                Me.disclaimerField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub ProcessRegisterCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessRegisterCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessRegisterCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RegisterResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RegisterResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub ProcessManageAccountCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessManageAccountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessManageAccountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ManageAccountResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ManageAccountResponse)
            End Get
        End Property
    End Class
End Namespace
