'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Endicia_DYMOStampService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DYMOStampsServiceSoap", [Namespace]:="www.envmgr.com/LabelService"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StampRateResponse)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(DataValidator))>  _
    Partial Public Class DYMOStampsService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetStampsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private validationRequestHeaderValueField As ValidationRequestHeader
        
        Private GetStampsXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private indiciumUserCredentialsValueField As IndiciumUserCredentials
        
        Private GetStampIndiciumOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalculateStampRatesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CalculateStampRatesXMLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.Endicia_DYMOStampsService_DYMOStampsService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property ValidationRequestHeaderValue() As ValidationRequestHeader
            Get
                Return Me.validationRequestHeaderValueField
            End Get
            Set
                Me.validationRequestHeaderValueField = value
            End Set
        End Property
        
        Public Property IndiciumUserCredentialsValue() As IndiciumUserCredentials
            Get
                Return Me.indiciumUserCredentialsValueField
            End Get
            Set
                Me.indiciumUserCredentialsValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetStampsCompleted As GetStampsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetStampsXMLCompleted As GetStampsXMLCompletedEventHandler
        
        '''<remarks/>
        Public Event GetStampIndiciumCompleted As GetStampIndiciumCompletedEventHandler
        
        '''<remarks/>
        Public Event CalculateStampRatesCompleted As CalculateStampRatesCompletedEventHandler
        
        '''<remarks/>
        Public Event CalculateStampRatesXMLCompleted As CalculateStampRatesXMLCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.envmgr.com/LabelService/GetStamps", RequestNamespace:="www.envmgr.com/LabelService", ResponseNamespace:="www.envmgr.com/LabelService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStamps(ByVal StampsRequest As StampsRequest) As <System.Xml.Serialization.XmlElementAttribute("StampsResponse")> StampsResponse
            Dim results() As Object = Me.Invoke("GetStamps", New Object() {StampsRequest})
            Return CType(results(0),StampsResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStampsAsync(ByVal StampsRequest As StampsRequest)
            Me.GetStampsAsync(StampsRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStampsAsync(ByVal StampsRequest As StampsRequest, ByVal userState As Object)
            If (Me.GetStampsOperationCompleted Is Nothing) Then
                Me.GetStampsOperationCompleted = AddressOf Me.OnGetStampsOperationCompleted
            End If
            Me.InvokeAsync("GetStamps", New Object() {StampsRequest}, Me.GetStampsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStampsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStampsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStampsCompleted(Me, New GetStampsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("ValidationRequestHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.envmgr.com/LabelService/GetStampsXML", RequestNamespace:="www.envmgr.com/LabelService", ResponseNamespace:="www.envmgr.com/LabelService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStampsXML(ByVal StampsRequestXML As String) As <System.Xml.Serialization.XmlElementAttribute("StampsResponse")> StampsResponse
            Dim results() As Object = Me.Invoke("GetStampsXML", New Object() {StampsRequestXML})
            Return CType(results(0),StampsResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStampsXMLAsync(ByVal StampsRequestXML As String)
            Me.GetStampsXMLAsync(StampsRequestXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStampsXMLAsync(ByVal StampsRequestXML As String, ByVal userState As Object)
            If (Me.GetStampsXMLOperationCompleted Is Nothing) Then
                Me.GetStampsXMLOperationCompleted = AddressOf Me.OnGetStampsXMLOperationCompleted
            End If
            Me.InvokeAsync("GetStampsXML", New Object() {StampsRequestXML}, Me.GetStampsXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStampsXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStampsXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStampsXMLCompleted(Me, New GetStampsXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("IndiciumUserCredentialsValue", Direction:=System.Web.Services.Protocols.SoapHeaderDirection.InOut),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.envmgr.com/LabelService/GetStampIndicium", RequestNamespace:="www.envmgr.com/LabelService", ResponseNamespace:="www.envmgr.com/LabelService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetStampIndicium(ByVal stampIndiciumRequest As StampIndiciumRequest, ByVal isTest As Boolean) As <System.Xml.Serialization.XmlElementAttribute("GeneratedIndiciumResponse")> GeneratedIndiciumResponse
            Dim results() As Object = Me.Invoke("GetStampIndicium", New Object() {stampIndiciumRequest, isTest})
            Return CType(results(0),GeneratedIndiciumResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetStampIndiciumAsync(ByVal stampIndiciumRequest As StampIndiciumRequest, ByVal isTest As Boolean)
            Me.GetStampIndiciumAsync(stampIndiciumRequest, isTest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetStampIndiciumAsync(ByVal stampIndiciumRequest As StampIndiciumRequest, ByVal isTest As Boolean, ByVal userState As Object)
            If (Me.GetStampIndiciumOperationCompleted Is Nothing) Then
                Me.GetStampIndiciumOperationCompleted = AddressOf Me.OnGetStampIndiciumOperationCompleted
            End If
            Me.InvokeAsync("GetStampIndicium", New Object() {stampIndiciumRequest, isTest}, Me.GetStampIndiciumOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetStampIndiciumOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetStampIndiciumCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetStampIndiciumCompleted(Me, New GetStampIndiciumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.envmgr.com/LabelService/CalculateStampRates", RequestNamespace:="www.envmgr.com/LabelService", ResponseNamespace:="www.envmgr.com/LabelService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalculateStampRates(ByVal StampsRateRequest As StampRatesRequest) As <System.Xml.Serialization.XmlElementAttribute("StampsRateResponse")> StampRatesResponse
            Dim results() As Object = Me.Invoke("CalculateStampRates", New Object() {StampsRateRequest})
            Return CType(results(0),StampRatesResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalculateStampRatesAsync(ByVal StampsRateRequest As StampRatesRequest)
            Me.CalculateStampRatesAsync(StampsRateRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalculateStampRatesAsync(ByVal StampsRateRequest As StampRatesRequest, ByVal userState As Object)
            If (Me.CalculateStampRatesOperationCompleted Is Nothing) Then
                Me.CalculateStampRatesOperationCompleted = AddressOf Me.OnCalculateStampRatesOperationCompleted
            End If
            Me.InvokeAsync("CalculateStampRates", New Object() {StampsRateRequest}, Me.CalculateStampRatesOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalculateStampRatesOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalculateStampRatesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalculateStampRatesCompleted(Me, New CalculateStampRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.envmgr.com/LabelService/CalculateStampRatesXML", RequestNamespace:="www.envmgr.com/LabelService", ResponseNamespace:="www.envmgr.com/LabelService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalculateStampRatesXML(ByVal StampRatesRequestXML As String) As <System.Xml.Serialization.XmlElementAttribute("StampsRateResponse")> StampRatesResponse
            Dim results() As Object = Me.Invoke("CalculateStampRatesXML", New Object() {StampRatesRequestXML})
            Return CType(results(0),StampRatesResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalculateStampRatesXMLAsync(ByVal StampRatesRequestXML As String)
            Me.CalculateStampRatesXMLAsync(StampRatesRequestXML, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalculateStampRatesXMLAsync(ByVal StampRatesRequestXML As String, ByVal userState As Object)
            If (Me.CalculateStampRatesXMLOperationCompleted Is Nothing) Then
                Me.CalculateStampRatesXMLOperationCompleted = AddressOf Me.OnCalculateStampRatesXMLOperationCompleted
            End If
            Me.InvokeAsync("CalculateStampRatesXML", New Object() {StampRatesRequestXML}, Me.CalculateStampRatesXMLOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalculateStampRatesXMLOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalculateStampRatesXMLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalculateStampRatesXMLCompleted(Me, New CalculateStampRatesXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="www.envmgr.com/LabelService", IsNullable:=false)>  _
    Partial Public Class ValidationRequestHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private validClientCodeField As String
        
        Private validClientNameField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property ValidClientCode() As String
            Get
                Return Me.validClientCodeField
            End Get
            Set
                Me.validClientCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidClientName() As String
            Get
                Return Me.validClientNameField
            End Get
            Set
                Me.validClientNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampRateEnumerator
        
        Private pieceshapeField As String
        
        Private mailClassField As String
        
        Private toCountryField As String
        
        Private weightOzField As Double
        
        Private rateField As Decimal
        
        '''<remarks/>
        Public Property Pieceshape() As String
            Get
                Return Me.pieceshapeField
            End Get
            Set
                Me.pieceshapeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MailClass() As String
            Get
                Return Me.mailClassField
            End Get
            Set
                Me.mailClassField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToCountry() As String
            Get
                Return Me.toCountryField
            End Get
            Set
                Me.toCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WeightOz() As Double
            Get
                Return Me.weightOzField
            End Get
            Set
                Me.weightOzField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Rate() As Decimal
            Get
                Return Me.rateField
            End Get
            Set
                Me.rateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampRatesResponse
        
        Private statusField As Integer
        
        Private errorMessageField As String
        
        Private stampRatesField() As StampRateEnumerator
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("StampRate")>  _
        Public Property StampRates() As StampRateEnumerator()
            Get
                Return Me.stampRatesField
            End Get
            Set
                Me.stampRatesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class GeneratedIndiciumResponse
        
        Private transactionIDField As String
        
        Private errorMessagePostageField As String
        
        Private hexaIndiciumField As String
        
        Private base64IBILiteField As String
        
        Private base64IBIField As String
        
        '''<remarks/>
        Public Property TransactionID() As String
            Get
                Return Me.transactionIDField
            End Get
            Set
                Me.transactionIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessagePostage() As String
            Get
                Return Me.errorMessagePostageField
            End Get
            Set
                Me.errorMessagePostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HexaIndicium() As String
            Get
                Return Me.hexaIndiciumField
            End Get
            Set
                Me.hexaIndiciumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Base64IBILite() As String
            Get
                Return Me.base64IBILiteField
            End Get
            Set
                Me.base64IBILiteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Base64IBI() As String
            Get
                Return Me.base64IBIField
            End Get
            Set
                Me.base64IBIField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(StampResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampRateResponse
        
        Private statusPostageField As Integer
        
        Private errorMessagePostageField As String
        
        Private perItemRateField As Decimal
        
        '''<remarks/>
        Public Property StatusPostage() As Integer
            Get
                Return Me.statusPostageField
            End Get
            Set
                Me.statusPostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessagePostage() As String
            Get
                Return Me.errorMessagePostageField
            End Get
            Set
                Me.errorMessagePostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PerItemRate() As Decimal
            Get
                Return Me.perItemRateField
            End Get
            Set
                Me.perItemRateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampResponse
        Inherits StampRateResponse
        
        Private successCountPostageField As Integer
        
        Private statusPrintingField As Integer
        
        Private errorMessagePrintingField As String
        
        Private successCountPrintingField As Integer
        
        Private totalRatesField As Decimal
        
        Private transactionIDsField() As Integer
        
        Private stampsRequestedField As Integer
        
        '''<remarks/>
        Public Property SuccessCountPostage() As Integer
            Get
                Return Me.successCountPostageField
            End Get
            Set
                Me.successCountPostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusPrinting() As Integer
            Get
                Return Me.statusPrintingField
            End Get
            Set
                Me.statusPrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessagePrinting() As String
            Get
                Return Me.errorMessagePrintingField
            End Get
            Set
                Me.errorMessagePrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuccessCountPrinting() As Integer
            Get
                Return Me.successCountPrintingField
            End Get
            Set
                Me.successCountPrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalRates() As Decimal
            Get
                Return Me.totalRatesField
            End Get
            Set
                Me.totalRatesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("TransactionID", IsNullable:=false)>  _
        Public Property TransactionIDs() As Integer()
            Get
                Return Me.transactionIDsField
            End Get
            Set
                Me.transactionIDsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StampsRequested() As Integer
            Get
                Return Me.stampsRequestedField
            End Get
            Set
                Me.stampsRequestedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampsResponse
        
        Private stampsRequestedField As Integer
        
        Private statusPostageField As Integer
        
        Private errorMessagePostageField As String
        
        Private successCountPostageField As Integer
        
        Private totalRateField As Decimal
        
        Private stampResponsesField() As StampResponse
        
        Private base64LabelImageField As String
        
        Private statusPrintingField As Integer
        
        Private errorMessagePrintingField As String
        
        Private successCountPrintingField As Integer
        
        Private postageBalanceField As Decimal
        
        Private imageDataField() As String
        
        Private controlDataField As Decimal
        
        '''<remarks/>
        Public Property StampsRequested() As Integer
            Get
                Return Me.stampsRequestedField
            End Get
            Set
                Me.stampsRequestedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusPostage() As Integer
            Get
                Return Me.statusPostageField
            End Get
            Set
                Me.statusPostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessagePostage() As String
            Get
                Return Me.errorMessagePostageField
            End Get
            Set
                Me.errorMessagePostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuccessCountPostage() As Integer
            Get
                Return Me.successCountPostageField
            End Get
            Set
                Me.successCountPostageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalRate() As Decimal
            Get
                Return Me.totalRateField
            End Get
            Set
                Me.totalRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StampResponses() As StampResponse()
            Get
                Return Me.stampResponsesField
            End Get
            Set
                Me.stampResponsesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Base64LabelImage() As String
            Get
                Return Me.base64LabelImageField
            End Get
            Set
                Me.base64LabelImageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusPrinting() As Integer
            Get
                Return Me.statusPrintingField
            End Get
            Set
                Me.statusPrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ErrorMessagePrinting() As String
            Get
                Return Me.errorMessagePrintingField
            End Get
            Set
                Me.errorMessagePrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuccessCountPrinting() As Integer
            Get
                Return Me.successCountPrintingField
            End Get
            Set
                Me.successCountPrintingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostageBalance() As Decimal
            Get
                Return Me.postageBalanceField
            End Get
            Set
                Me.postageBalanceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Base64LabelImage")>  _
        Public Property ImageData() As String()
            Get
                Return Me.imageDataField
            End Get
            Set
                Me.imageDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ControlData() As Decimal
            Get
                Return Me.controlDataField
            End Get
            Set
                Me.controlDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class CertifiedIntermediary
        
        Private accountIDField As String
        
        Private passPhraseField As String
        
        Private tokenField As String
        
        Private tokenTimeStampField As String
        
        '''<remarks/>
        Public Property AccountID() As String
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PassPhrase() As String
            Get
                Return Me.passPhraseField
            End Get
            Set
                Me.passPhraseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TokenTimeStamp() As String
            Get
                Return Me.tokenTimeStampField
            End Get
            Set
                Me.tokenTimeStampField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(StampRatesRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StampRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StampIndiciumRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StampsRateRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StampsRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class DataValidator
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampRatesRequest
        Inherits DataValidator
        
        Private tokenField As String
        
        Private isTestField As Boolean
        
        Private certifiedIntermediaryField As CertifiedIntermediary
        
        Private requesterIDField As String
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsTest() As Boolean
            Get
                Return Me.isTestField
            End Get
            Set
                Me.isTestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CertifiedIntermediary() As CertifiedIntermediary
            Get
                Return Me.certifiedIntermediaryField
            End Get
            Set
                Me.certifiedIntermediaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequesterID() As String
            Get
                Return Me.requesterIDField
            End Get
            Set
                Me.requesterIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(StampIndiciumRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampRequest
        Inherits DataValidator
        
        Private mailpieceShapeField As String
        
        Private mailClassField As String
        
        Private toCountryCodeField As String
        
        Private weightOzField As Double
        
        Private useUserRateField As String
        
        Private userRateField As Decimal
        
        Private countField As Integer
        
        Private machinableField As String
        
        Private dateField As String
        
        '''<remarks/>
        Public Property MailpieceShape() As String
            Get
                Return Me.mailpieceShapeField
            End Get
            Set
                Me.mailpieceShapeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MailClass() As String
            Get
                Return Me.mailClassField
            End Get
            Set
                Me.mailClassField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ToCountryCode() As String
            Get
                Return Me.toCountryCodeField
            End Get
            Set
                Me.toCountryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WeightOz() As Double
            Get
                Return Me.weightOzField
            End Get
            Set
                Me.weightOzField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseUserRate() As String
            Get
                Return Me.useUserRateField
            End Get
            Set
                Me.useUserRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserRate() As Decimal
            Get
                Return Me.userRateField
            End Get
            Set
                Me.userRateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Machinable() As String
            Get
                Return Me.machinableField
            End Get
            Set
                Me.machinableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampIndiciumRequest
        Inherits StampRequest
        
        Private accountIDField As String
        
        Private passPhraseField As String
        
        Private softwareIDField As SoftwareID
        
        '''<remarks/>
        Public Property AccountID() As String
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PassPhrase() As String
            Get
                Return Me.passPhraseField
            End Get
            Set
                Me.passPhraseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property softwareID() As SoftwareID
            Get
                Return Me.softwareIDField
            End Get
            Set
                Me.softwareIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Public Enum SoftwareID
        
        '''<remarks/>
        LabelService
        
        '''<remarks/>
        PictureItPostage
        
        '''<remarks/>
        SheetStamps
        
        '''<remarks/>
        RobotBuy
        
        '''<remarks/>
        DAZzle
        
        '''<remarks/>
        EndiciaForMac
        
        '''<remarks/>
        RSSPostage
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(StampsRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampsRateRequest
        Inherits DataValidator
        
        Private passPhraseField As String
        
        Private shipDateField As String
        
        Private shipTimeField As String
        
        Private extensionField As String
        
        Private dateAdvanceField As Integer
        
        Private stampRequestsField() As StampRequest
        
        Private tokenField As String
        
        Private accountIDField As String
        
        '''<remarks/>
        Public Property PassPhrase() As String
            Get
                Return Me.passPhraseField
            End Get
            Set
                Me.passPhraseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipDate() As String
            Get
                Return Me.shipDateField
            End Get
            Set
                Me.shipDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShipTime() As String
            Get
                Return Me.shipTimeField
            End Get
            Set
                Me.shipTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Extension() As String
            Get
                Return Me.extensionField
            End Get
            Set
                Me.extensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateAdvance() As Integer
            Get
                Return Me.dateAdvanceField
            End Get
            Set
                Me.dateAdvanceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StampRequests() As StampRequest()
            Get
                Return Me.stampRequestsField
            End Get
            Set
                Me.stampRequestsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountID() As String
            Get
                Return Me.accountIDField
            End Get
            Set
                Me.accountIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService")>  _
    Partial Public Class StampsRequest
        Inherits StampsRateRequest
        
        Private mediaTypeField As String
        
        Private xOffsetField As Decimal
        
        Private yOffsetField As Decimal
        
        Private xStartLabelField As Integer
        
        Private yStartLabelField As Integer
        
        Private activationCodeField As String
        
        Private referenceIDField As String
        
        Private requesterIDField As String
        
        Private testField As String
        
        Private imageFormatField As String
        
        '''<remarks/>
        Public Property MediaType() As String
            Get
                Return Me.mediaTypeField
            End Get
            Set
                Me.mediaTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XOffset() As Decimal
            Get
                Return Me.xOffsetField
            End Get
            Set
                Me.xOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property YOffset() As Decimal
            Get
                Return Me.yOffsetField
            End Get
            Set
                Me.yOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XStartLabel() As Integer
            Get
                Return Me.xStartLabelField
            End Get
            Set
                Me.xStartLabelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property YStartLabel() As Integer
            Get
                Return Me.yStartLabelField
            End Get
            Set
                Me.yStartLabelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActivationCode() As String
            Get
                Return Me.activationCodeField
            End Get
            Set
                Me.activationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReferenceID() As String
            Get
                Return Me.referenceIDField
            End Get
            Set
                Me.referenceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequesterID() As String
            Get
                Return Me.requesterIDField
            End Get
            Set
                Me.requesterIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Test() As String
            Get
                Return Me.testField
            End Get
            Set
                Me.testField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ImageFormat() As String
            Get
                Return Me.imageFormatField
            End Get
            Set
                Me.imageFormatField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.envmgr.com/LabelService"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="www.envmgr.com/LabelService", IsNullable:=false)>  _
    Partial Public Class IndiciumUserCredentials
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub GetStampsCompletedEventHandler(ByVal sender As Object, ByVal e As GetStampsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStampsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StampsResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StampsResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub GetStampsXMLCompletedEventHandler(ByVal sender As Object, ByVal e As GetStampsXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStampsXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StampsResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StampsResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub GetStampIndiciumCompletedEventHandler(ByVal sender As Object, ByVal e As GetStampIndiciumCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetStampIndiciumCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GeneratedIndiciumResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeneratedIndiciumResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub CalculateStampRatesCompletedEventHandler(ByVal sender As Object, ByVal e As CalculateStampRatesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalculateStampRatesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StampRatesResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StampRatesResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub CalculateStampRatesXMLCompletedEventHandler(ByVal sender As Object, ByVal e As CalculateStampRatesXMLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalculateStampRatesXMLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StampRatesResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StampRatesResponse)
            End Get
        End Property
    End Class
End Namespace
