'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace FedEx_AddressValidationService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AddressValidationServiceSoapBinding", [Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressValidationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private addressValidationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.FedEx_AddressValidationService_AddressValidationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event addressValidationCompleted As addressValidationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/addressvalidation/v4/addressValidation", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function addressValidation(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")> ByVal AddressValidationRequest As AddressValidationRequest) As <System.Xml.Serialization.XmlElementAttribute("AddressValidationReply", [Namespace]:="http://fedex.com/ws/addressvalidation/v4")> AddressValidationReply
            Dim results() As Object = Me.Invoke("addressValidation", New Object() {AddressValidationRequest})
            Return CType(results(0),AddressValidationReply)
        End Function
        
        '''<remarks/>
        Public Overloads Sub addressValidationAsync(ByVal AddressValidationRequest As AddressValidationRequest)
            Me.addressValidationAsync(AddressValidationRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub addressValidationAsync(ByVal AddressValidationRequest As AddressValidationRequest, ByVal userState As Object)
            If (Me.addressValidationOperationCompleted Is Nothing) Then
                Me.addressValidationOperationCompleted = AddressOf Me.OnaddressValidationOperationCompleted
            End If
            Me.InvokeAsync("addressValidation", New Object() {AddressValidationRequest}, Me.addressValidationOperationCompleted, userState)
        End Sub
        
        Private Sub OnaddressValidationOperationCompleted(ByVal arg As Object)
            If (Not (Me.addressValidationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent addressValidationCompleted(Me, New addressValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressValidationRequest
        
        Private webAuthenticationDetailField As WebAuthenticationDetail
        
        Private clientDetailField As ClientDetail
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private inEffectAsOfTimestampField As Date
        
        Private inEffectAsOfTimestampFieldSpecified As Boolean
        
        Private addressesToValidateField() As AddressToValidate
        
        '''<remarks/>
        Public Property WebAuthenticationDetail() As WebAuthenticationDetail
            Get
                Return Me.webAuthenticationDetailField
            End Get
            Set
                Me.webAuthenticationDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientDetail() As ClientDetail
            Get
                Return Me.clientDetailField
            End Get
            Set
                Me.clientDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InEffectAsOfTimestamp() As Date
            Get
                Return Me.inEffectAsOfTimestampField
            End Get
            Set
                Me.inEffectAsOfTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property InEffectAsOfTimestampSpecified() As Boolean
            Get
                Return Me.inEffectAsOfTimestampFieldSpecified
            End Get
            Set
                Me.inEffectAsOfTimestampFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressesToValidate")>  _
        Public Property AddressesToValidate() As AddressToValidate()
            Get
                Return Me.addressesToValidateField
            End Get
            Set
                Me.addressesToValidateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class WebAuthenticationDetail
        
        Private parentCredentialField As WebAuthenticationCredential
        
        Private userCredentialField As WebAuthenticationCredential
        
        '''<remarks/>
        Public Property ParentCredential() As WebAuthenticationCredential
            Get
                Return Me.parentCredentialField
            End Get
            Set
                Me.parentCredentialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserCredential() As WebAuthenticationCredential
            Get
                Return Me.userCredentialField
            End Get
            Set
                Me.userCredentialField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class WebAuthenticationCredential
        
        Private keyField As String
        
        Private passwordField As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressAttribute
        
        Private nameField As String
        
        Private valueField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class ParsedPostalCodeDetail
        
        Private baseField As String
        
        Private addOnField As String
        
        Private deliveryPointField As String
        
        '''<remarks/>
        Public Property Base() As String
            Get
                Return Me.baseField
            End Get
            Set
                Me.baseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AddOn() As String
            Get
                Return Me.addOnField
            End Get
            Set
                Me.addOnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeliveryPoint() As String
            Get
                Return Me.deliveryPointField
            End Get
            Set
                Me.deliveryPointField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class ParsedStreetLineDetail
        
        Private houseNumberField As String
        
        Private preStreetTypeField As String
        
        Private leadingDirectionalField As String
        
        Private streetNameField As String
        
        Private streetSuffixField As String
        
        Private trailingDirectionalField As String
        
        Private unitLabelField As String
        
        Private unitNumberField As String
        
        Private ruralRouteField As String
        
        Private pOBoxField As String
        
        Private buildingField As String
        
        Private organizationField As String
        
        '''<remarks/>
        Public Property HouseNumber() As String
            Get
                Return Me.houseNumberField
            End Get
            Set
                Me.houseNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PreStreetType() As String
            Get
                Return Me.preStreetTypeField
            End Get
            Set
                Me.preStreetTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LeadingDirectional() As String
            Get
                Return Me.leadingDirectionalField
            End Get
            Set
                Me.leadingDirectionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetName() As String
            Get
                Return Me.streetNameField
            End Get
            Set
                Me.streetNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StreetSuffix() As String
            Get
                Return Me.streetSuffixField
            End Get
            Set
                Me.streetSuffixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TrailingDirectional() As String
            Get
                Return Me.trailingDirectionalField
            End Get
            Set
                Me.trailingDirectionalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnitLabel() As String
            Get
                Return Me.unitLabelField
            End Get
            Set
                Me.unitLabelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnitNumber() As String
            Get
                Return Me.unitNumberField
            End Get
            Set
                Me.unitNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RuralRoute() As String
            Get
                Return Me.ruralRouteField
            End Get
            Set
                Me.ruralRouteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property POBox() As String
            Get
                Return Me.pOBoxField
            End Get
            Set
                Me.pOBoxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Building() As String
            Get
                Return Me.buildingField
            End Get
            Set
                Me.buildingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Organization() As String
            Get
                Return Me.organizationField
            End Get
            Set
                Me.organizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class ParsedAddressPartsDetail
        
        Private parsedStreetLineField As ParsedStreetLineDetail
        
        Private parsedPostalCodeField As ParsedPostalCodeDetail
        
        '''<remarks/>
        Public Property ParsedStreetLine() As ParsedStreetLineDetail
            Get
                Return Me.parsedStreetLineField
            End Get
            Set
                Me.parsedStreetLineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParsedPostalCode() As ParsedPostalCodeDetail
            Get
                Return Me.parsedPostalCodeField
            End Get
            Set
                Me.parsedPostalCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressValidationResult
        
        Private clientReferenceIdField As String
        
        Private stateField As OperationalAddressStateType
        
        Private stateFieldSpecified As Boolean
        
        Private classificationField As FedExAddressClassificationType
        
        Private classificationFieldSpecified As Boolean
        
        Private effectiveContactField As Contact
        
        Private effectiveAddressField As Address
        
        Private parsedAddressPartsDetailField As ParsedAddressPartsDetail
        
        Private attributesField() As AddressAttribute
        
        '''<remarks/>
        Public Property ClientReferenceId() As String
            Get
                Return Me.clientReferenceIdField
            End Get
            Set
                Me.clientReferenceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property State() As OperationalAddressStateType
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StateSpecified() As Boolean
            Get
                Return Me.stateFieldSpecified
            End Get
            Set
                Me.stateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Classification() As FedExAddressClassificationType
            Get
                Return Me.classificationField
            End Get
            Set
                Me.classificationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ClassificationSpecified() As Boolean
            Get
                Return Me.classificationFieldSpecified
            End Get
            Set
                Me.classificationFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EffectiveContact() As Contact
            Get
                Return Me.effectiveContactField
            End Get
            Set
                Me.effectiveContactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EffectiveAddress() As Address
            Get
                Return Me.effectiveAddressField
            End Get
            Set
                Me.effectiveAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParsedAddressPartsDetail() As ParsedAddressPartsDetail
            Get
                Return Me.parsedAddressPartsDetailField
            End Get
            Set
                Me.parsedAddressPartsDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Attributes")>  _
        Public Property Attributes() As AddressAttribute()
            Get
                Return Me.attributesField
            End Get
            Set
                Me.attributesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Public Enum OperationalAddressStateType
        
        '''<remarks/>
        NORMALIZED
        
        '''<remarks/>
        RAW
        
        '''<remarks/>
        STANDARDIZED
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Public Enum FedExAddressClassificationType
        
        '''<remarks/>
        BUSINESS
        
        '''<remarks/>
        MIXED
        
        '''<remarks/>
        RESIDENTIAL
        
        '''<remarks/>
        UNKNOWN
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class Contact
        
        Private contactIdField As String
        
        Private personNameField As String
        
        Private titleField As String
        
        Private companyNameField As String
        
        Private phoneNumberField As String
        
        Private phoneExtensionField As String
        
        Private tollFreePhoneNumberField As String
        
        Private pagerNumberField As String
        
        Private faxNumberField As String
        
        Private eMailAddressField As String
        
        '''<remarks/>
        Public Property ContactId() As String
            Get
                Return Me.contactIdField
            End Get
            Set
                Me.contactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonName() As String
            Get
                Return Me.personNameField
            End Get
            Set
                Me.personNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneExtension() As String
            Get
                Return Me.phoneExtensionField
            End Get
            Set
                Me.phoneExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TollFreePhoneNumber() As String
            Get
                Return Me.tollFreePhoneNumberField
            End Get
            Set
                Me.tollFreePhoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PagerNumber() As String
            Get
                Return Me.pagerNumberField
            End Get
            Set
                Me.pagerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FaxNumber() As String
            Get
                Return Me.faxNumberField
            End Get
            Set
                Me.faxNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMailAddress() As String
            Get
                Return Me.eMailAddressField
            End Get
            Set
                Me.eMailAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class Address
        
        Private streetLinesField() As String
        
        Private cityField As String
        
        Private stateOrProvinceCodeField As String
        
        Private postalCodeField As String
        
        Private urbanizationCodeField As String
        
        Private countryCodeField As String
        
        Private countryNameField As String
        
        Private residentialField As Boolean
        
        Private residentialFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("StreetLines")>  _
        Public Property StreetLines() As String()
            Get
                Return Me.streetLinesField
            End Get
            Set
                Me.streetLinesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StateOrProvinceCode() As String
            Get
                Return Me.stateOrProvinceCodeField
            End Get
            Set
                Me.stateOrProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UrbanizationCode() As String
            Get
                Return Me.urbanizationCodeField
            End Get
            Set
                Me.urbanizationCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryName() As String
            Get
                Return Me.countryNameField
            End Get
            Set
                Me.countryNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Residential() As Boolean
            Get
                Return Me.residentialField
            End Get
            Set
                Me.residentialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ResidentialSpecified() As Boolean
            Get
                Return Me.residentialFieldSpecified
            End Get
            Set
                Me.residentialFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class NotificationParameter
        
        Private idField As String
        
        Private valueField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class Notification
        
        Private severityField As NotificationSeverityType
        
        Private severityFieldSpecified As Boolean
        
        Private sourceField As String
        
        Private codeField As String
        
        Private messageField As String
        
        Private localizedMessageField As String
        
        Private messageParametersField() As NotificationParameter
        
        '''<remarks/>
        Public Property Severity() As NotificationSeverityType
            Get
                Return Me.severityField
            End Get
            Set
                Me.severityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SeveritySpecified() As Boolean
            Get
                Return Me.severityFieldSpecified
            End Get
            Set
                Me.severityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocalizedMessage() As String
            Get
                Return Me.localizedMessageField
            End Get
            Set
                Me.localizedMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MessageParameters")>  _
        Public Property MessageParameters() As NotificationParameter()
            Get
                Return Me.messageParametersField
            End Get
            Set
                Me.messageParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Public Enum NotificationSeverityType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        FAILURE
        
        '''<remarks/>
        NOTE
        
        '''<remarks/>
        SUCCESS
        
        '''<remarks/>
        WARNING
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressValidationReply
        
        Private highestSeverityField As NotificationSeverityType
        
        Private notificationsField() As Notification
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private replyTimestampField As Date
        
        Private replyTimestampFieldSpecified As Boolean
        
        Private addressResultsField() As AddressValidationResult
        
        '''<remarks/>
        Public Property HighestSeverity() As NotificationSeverityType
            Get
                Return Me.highestSeverityField
            End Get
            Set
                Me.highestSeverityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Notifications")>  _
        Public Property Notifications() As Notification()
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReplyTimestamp() As Date
            Get
                Return Me.replyTimestampField
            End Get
            Set
                Me.replyTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReplyTimestampSpecified() As Boolean
            Get
                Return Me.replyTimestampFieldSpecified
            End Get
            Set
                Me.replyTimestampFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("AddressResults")>  _
        Public Property AddressResults() As AddressValidationResult()
            Get
                Return Me.addressResultsField
            End Get
            Set
                Me.addressResultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class TransactionDetail
        
        Private customerTransactionIdField As String
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property CustomerTransactionId() As String
            Get
                Return Me.customerTransactionIdField
            End Get
            Set
                Me.customerTransactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class Localization
        
        Private languageCodeField As String
        
        Private localeCodeField As String
        
        '''<remarks/>
        Public Property LanguageCode() As String
            Get
                Return Me.languageCodeField
            End Get
            Set
                Me.languageCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocaleCode() As String
            Get
                Return Me.localeCodeField
            End Get
            Set
                Me.localeCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class VersionId
        
        Private serviceIdField As String
        
        Private majorField As Integer
        
        Private intermediateField As Integer
        
        Private minorField As Integer
        
        Public Sub New()
            MyBase.New
            Me.serviceIdField = "aval"
            Me.majorField = 4
            Me.intermediateField = 0
            Me.minorField = 0
        End Sub
        
        '''<remarks/>
        Public Property ServiceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Major() As Integer
            Get
                Return Me.majorField
            End Get
            Set
                Me.majorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Intermediate() As Integer
            Get
                Return Me.intermediateField
            End Get
            Set
                Me.intermediateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Minor() As Integer
            Get
                Return Me.minorField
            End Get
            Set
                Me.minorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class AddressToValidate
        
        Private clientReferenceIdField As String
        
        Private contactField As Contact
        
        Private addressField As Address
        
        '''<remarks/>
        Public Property ClientReferenceId() As String
            Get
                Return Me.clientReferenceIdField
            End Get
            Set
                Me.clientReferenceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Contact() As Contact
            Get
                Return Me.contactField
            End Get
            Set
                Me.contactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/addressvalidation/v4")>  _
    Partial Public Class ClientDetail
        
        Private accountNumberField As String
        
        Private meterNumberField As String
        
        Private integratorIdField As String
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MeterNumber() As String
            Get
                Return Me.meterNumberField
            End Get
            Set
                Me.meterNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IntegratorId() As String
            Get
                Return Me.integratorIdField
            End Get
            Set
                Me.integratorIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub addressValidationCompletedEventHandler(ByVal sender As Object, ByVal e As addressValidationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class addressValidationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AddressValidationReply
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AddressValidationReply)
            End Get
        End Property
    End Class
End Namespace
