'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Ship")>  _
    Public ReadOnly Property UPS_WebReference_ShipService() As String
        Get
            Return CType(Me("UPS_WebReference_ShipService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Registration")>  _
    Public ReadOnly Property UPS_RegWebReference_RegisterMgrAcctService() As String
        Get
            Return CType(Me("UPS_RegWebReference_RegisterMgrAcctService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/TimeInTransit")>  _
    Public ReadOnly Property UPS_TinTWebReference_TimeInTransitService() As String
        Get
            Return CType(Me("UPS_TinTWebReference_TimeInTransitService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices/Void")>  _
    Public ReadOnly Property UPS_VoidWebReference_VoidService() As String
        Get
            Return CType(Me("UPS_VoidWebReference_VoidService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property StoreOwner_Username() As String
        Get
            Return CType(Me("StoreOwner_Username"),String)
        End Get
        Set
            Me("StoreOwner_Username") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property StoreOwner_Password() As String
        Get
            Return CType(Me("StoreOwner_Password"),String)
        End Get
        Set
            Me("StoreOwner_Password") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/webservices")>  _
    Public Property UPS_production_url() As String
        Get
            Return CType(Me("UPS_production_url"),String)
        End Get
        Set
            Me("UPS_production_url") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://wwwcie.ups.com/webservices")>  _
    Public Property UPS_test_url() As String
        Get
            Return CType(Me("UPS_test_url"),String)
        End Get
        Set
            Me("UPS_test_url") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services")>  _
    Public ReadOnly Property FedEx_RegistrationService_RegistrationService() As String
        Get
            Return CType(Me("FedEx_RegistrationService_RegistrationService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/ship")>  _
    Public ReadOnly Property FedEx_ShipService_ShipService() As String
        Get
            Return CType(Me("FedEx_ShipService_ShipService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/rate")>  _
    Public ReadOnly Property FedEx_RateService_RateService() As String
        Get
            Return CType(Me("FedEx_RateService_RateService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/addressvalidation")>  _
    Public ReadOnly Property FedEx_AddressValidationService_AddressValidationService() As String
        Get
            Return CType(Me("FedEx_AddressValidationService_AddressValidationService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/close")>  _
    Public ReadOnly Property FedEx_CloseService_CloseService() As String
        Get
            Return CType(Me("FedEx_CloseService_CloseService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/openship")>  _
    Public ReadOnly Property FedEx_OpenShipService_OpenShipService() As String
        Get
            Return CType(Me("FedEx_OpenShipService_OpenShipService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://ws.fedex.com:443/web-services/scanposting")>  _
    Public ReadOnly Property FedEx_ScanPostingService_ScanPostingService() As String
        Get
            Return CType(Me("FedEx_ScanPostingService_ScanPostingService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://labelserver.endicia.com/LabelService/EwsLabelService.asmx")>  _
    Public ReadOnly Property Endicia_EwsLabelService_EwsLabelService() As String
        Get
            Return CType(Me("Endicia_EwsLabelService_EwsLabelService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://labelserver.endicia.com/LabelService/DYMOStampsservice.asmx")>  _
    Public ReadOnly Property Endicia_DYMOStampsService_DYMOStampsService() As String
        Get
            Return CType(Me("Endicia_DYMOStampsService_DYMOStampsService"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
    Public Property Endicia_LastPostageAmountAdded() As Double
        Get
            Return CType(Me("Endicia_LastPostageAmountAdded"),Double)
        End Get
        Set
            Me("Endicia_LastPostageAmountAdded") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property PackMaster_Print_Details_OnReceipt() As Boolean
        Get
            Return CType(Me("PackMaster_Print_Details_OnReceipt"),Boolean)
        End Get
        Set
            Me("PackMaster_Print_Details_OnReceipt") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DropOff_chkPrintReceipt() As Boolean
        Get
            Return CType(Me("DropOff_chkPrintReceipt"),Boolean)
        End Get
        Set
            Me("DropOff_chkPrintReceipt") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DropOff_chkSendEmails() As Boolean
        Get
            Return CType(Me("DropOff_chkSendEmails"),Boolean)
        End Get
        Set
            Me("DropOff_chkSendEmails") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DropOff_chkSendSMS() As Boolean
        Get
            Return CType(Me("DropOff_chkSendSMS"),Boolean)
        End Get
        Set
            Me("DropOff_chkSendSMS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Other")>  _
    Public Property DropOff_CarrierOther() As String
        Get
            Return CType(Me("DropOff_CarrierOther"),String)
        End Get
        Set
            Me("DropOff_CarrierOther") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property PackageValet_JPNReceiptCopies() As Integer
        Get
            Return CType(Me("PackageValet_JPNReceiptCopies"),Integer)
        End Get
        Set
            Me("PackageValet_JPNReceiptCopies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property PackageValet_JPNLabelCopies() As Integer
        Get
            Return CType(Me("PackageValet_JPNLabelCopies"),Integer)
        End Get
        Set
            Me("PackageValet_JPNLabelCopies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property PackageValet_JSSLaserCopies() As Integer
        Get
            Return CType(Me("PackageValet_JSSLaserCopies"),Integer)
        End Get
        Set
            Me("PackageValet_JSSLaserCopies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property PackageValet_JPLLabelCopies() As Integer
        Get
            Return CType(Me("PackageValet_JPLLabelCopies"),Integer)
        End Get
        Set
            Me("PackageValet_JPLLabelCopies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Notify_Email() As String
        Get
            Return CType(Me("Notify_Email"),String)
        End Get
        Set
            Me("Notify_Email") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Notify_Password() As String
        Get
            Return CType(Me("Notify_Password"),String)
        End Get
        Set
            Me("Notify_Password") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Notify_SmtpServer() As String
        Get
            Return CType(Me("Notify_SmtpServer"),String)
        End Get
        Set
            Me("Notify_SmtpServer") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Notify_SmtpPort() As String
        Get
            Return CType(Me("Notify_SmtpPort"),String)
        End Get
        Set
            Me("Notify_SmtpPort") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Notify_KeepLog() As Boolean
        Get
            Return CType(Me("Notify_KeepLog"),Boolean)
        End Get
        Set
            Me("Notify_KeepLog") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Notify_SendCopy() As Boolean
        Get
            Return CType(Me("Notify_SendCopy"),Boolean)
        End Get
        Set
            Me("Notify_SendCopy") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Notify_SmtpEncrypted() As Boolean
        Get
            Return CType(Me("Notify_SmtpEncrypted"),Boolean)
        End Get
        Set
            Me("Notify_SmtpEncrypted") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PackageValet_CheckIn_PrintNotice() As Boolean
        Get
            Return CType(Me("PackageValet_CheckIn_PrintNotice"),Boolean)
        End Get
        Set
            Me("PackageValet_CheckIn_PrintNotice") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PackageValet_CheckIn_PrintLabel() As Boolean
        Get
            Return CType(Me("PackageValet_CheckIn_PrintLabel"),Boolean)
        End Get
        Set
            Me("PackageValet_CheckIn_PrintLabel") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PackageValet_CheckIn_PrintSignatureSheet() As Boolean
        Get
            Return CType(Me("PackageValet_CheckIn_PrintSignatureSheet"),Boolean)
        End Get
        Set
            Me("PackageValet_CheckIn_PrintSignatureSheet") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PackageValet_CheckIn_SendSMS() As Boolean
        Get
            Return CType(Me("PackageValet_CheckIn_SendSMS"),Boolean)
        End Get
        Set
            Me("PackageValet_CheckIn_SendSMS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PackageValet_CheckIn_SendEmail() As Boolean
        Get
            Return CType(Me("PackageValet_CheckIn_SendEmail"),Boolean)
        End Get
        Set
            Me("PackageValet_CheckIn_SendEmail") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property PackageValet_CheckIn_NoticePrintOption() As Byte
        Get
            Return CType(Me("PackageValet_CheckIn_NoticePrintOption"),Byte)
        End Get
        Set
            Me("PackageValet_CheckIn_NoticePrintOption") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DropOff_chkAutoDetect() As Boolean
        Get
            Return CType(Me("DropOff_chkAutoDetect"),Boolean)
        End Get
        Set
            Me("DropOff_chkAutoDetect") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://xmlpitest-ea.dhl.com/XMLShippingServlet")>  _
    Public ReadOnly Property DHL_XML_Test_Url() As String
        Get
            Return CType(Me("DHL_XML_Test_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://xmlpi-ea.dhl.com/XMLShippingServlet")>  _
    Public ReadOnly Property DHL_XML_Production_Url() As String
        Get
            Return CType(Me("DHL_XML_Production_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property DHL_XML_IsTest() As Boolean
        Get
            Return CType(Me("DHL_XML_IsTest"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://b2c.ams1907.com")>  _
    Public ReadOnly Property UPS_DropOff_Test_Url() As String
        Get
            Return CType(Me("UPS_DropOff_Test_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://b2c.ups.com")>  _
    Public ReadOnly Property UPS_DropOff_Production_Url() As String
        Get
            Return CType(Me("UPS_DropOff_Production_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public ReadOnly Property UPS_DropOff_IsTest() As Boolean
        Get
            Return CType(Me("UPS_DropOff_IsTest"),Boolean)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MBXDailyNotice_chkEmail() As Boolean
        Get
            Return CType(Me("MBXDailyNotice_chkEmail"),Boolean)
        End Get
        Set
            Me("MBXDailyNotice_chkEmail") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MBXDailyNotice_chkSMS() As Boolean
        Get
            Return CType(Me("MBXDailyNotice_chkSMS"),Boolean)
        End Get
        Set
            Me("MBXDailyNotice_chkSMS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("576")>  _
    Public Property Window_Height() As String
        Get
            Return CType(Me("Window_Height"),String)
        End Get
        Set
            Me("Window_Height") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1024")>  _
    Public Property Window_Width() As String
        Get
            Return CType(Me("Window_Width"),String)
        End Get
        Set
            Me("Window_Width") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Window_IsMaximized() As Boolean
        Get
            Return CType(Me("Window_IsMaximized"),Boolean)
        End Get
        Set
            Me("Window_IsMaximized") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("90")>  _
    Public Property POS_InvoiceHistory_DaysToShow() As Integer
        Get
            Return CType(Me("POS_InvoiceHistory_DaysToShow"),Integer)
        End Get
        Set
            Me("POS_InvoiceHistory_DaysToShow") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property Contacts_SearchType() As Integer
        Get
            Return CType(Me("Contacts_SearchType"),Integer)
        End Get
        Set
            Me("Contacts_SearchType") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Use_Store_From_Address() As Boolean
        Get
            Return CType(Me("Use_Store_From_Address"),Boolean)
        End Get
        Set
            Me("Use_Store_From_Address") = value
        End Set
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/api/webservices/TimeInTransit")>  _
    Public ReadOnly Property UPS_Steppingstone_TinT_Url() As String
        Get
            Return CType(Me("UPS_Steppingstone_TinT_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/api/webservices/Ship")>  _
    Public ReadOnly Property UPS_Steppingstone_Ship_Url() As String
        Get
            Return CType(Me("UPS_Steppingstone_Ship_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://onlinetools.ups.com/api/webservices/Void")>  _
    Public ReadOnly Property UPS_Steppingstone_Void_Url() As String
        Get
            Return CType(Me("UPS_Steppingstone_Void_Url"),String)
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property DropOff_FocusTracking() As Boolean
        Get
            Return CType(Me("DropOff_FocusTracking"),Boolean)
        End Get
        Set
            Me("DropOff_FocusTracking") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Enable_ReceiptView() As Boolean
        Get
            Return CType(Me("Enable_ReceiptView"),Boolean)
        End Get
        Set
            Me("Enable_ReceiptView") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Suggest_BoxSelections() As Boolean
        Get
            Return CType(Me("Suggest_BoxSelections"),Boolean)
        End Get
        Set
            Me("Suggest_BoxSelections") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SHIPRITE.MySettings
            Get
                Return Global.SHIPRITE.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
