'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Net
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UPS_TinTWebReference

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="TimeInTransitBinding", [Namespace]:="http://www.ups.com/WSDL/XOLTWS/TNT/v1.0")>
    Partial Public Class TimeInTransitService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private uPSSecurityValueField As UPSSecurity

        Private ProcessTimeInTransitOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.UPS_TinTWebReference_TimeInTransitService
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Property UPSSecurityValue() As UPSSecurity
            Get
                Return Me.uPSSecurityValueField
            End Get
            Set
                Me.uPSSecurityValueField = Value
            End Set
        End Property

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                            AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
                    MyBase.UseDefaultCredentials = False
                End If
                MyBase.Url = Value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = Value
                Me.useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        Public ReadOnly Property WebRequest() As Net.WebRequest
            Get
                Return GetWebRequest(New Uri(Me.Url))
            End Get
        End Property

        Public Property AccessToken As String

        Protected Overrides Function GetWebRequest(uri As Uri) As Net.WebRequest
            Dim req As HttpWebRequest = CType(MyBase.GetWebRequest(uri), HttpWebRequest)
            If Not String.IsNullOrWhiteSpace(AccessToken) Then
                req.Headers.Add(HttpRequestHeader.Authorization, "Bearer " & AccessToken)
            End If
            Return req
        End Function

        '''<remarks/>
        Public Event ProcessTimeInTransitCompleted As ProcessTimeInTransitCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue"),
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/TimeInTransitBinding/v1.0", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>
        Public Function ProcessTimeInTransit(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")> ByVal TimeInTransitRequest As TimeInTransitRequest) As <System.Xml.Serialization.XmlElementAttribute("TimeInTransitResponse", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")> TimeInTransitResponse
            Dim results() As Object = Me.Invoke("ProcessTimeInTransit", New Object() {TimeInTransitRequest})
            Return CType(results(0), TimeInTransitResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub ProcessTimeInTransitAsync(ByVal TimeInTransitRequest As TimeInTransitRequest)
            Me.ProcessTimeInTransitAsync(TimeInTransitRequest, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ProcessTimeInTransitAsync(ByVal TimeInTransitRequest As TimeInTransitRequest, ByVal userState As Object)
            If (Me.ProcessTimeInTransitOperationCompleted Is Nothing) Then
                Me.ProcessTimeInTransitOperationCompleted = AddressOf Me.OnProcessTimeInTransitOperationCompleted
            End If
            Me.InvokeAsync("ProcessTimeInTransit", New Object() {TimeInTransitRequest}, Me.ProcessTimeInTransitOperationCompleted, userState)
        End Sub

        Private Sub OnProcessTimeInTransitOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessTimeInTransitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessTimeInTransitCompleted(Me, New ProcessTimeInTransitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                Return False
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024) _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return True
            End If
            Return False
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0"),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable:=False)>
    Partial Public Class UPSSecurity
        Inherits System.Web.Services.Protocols.SoapHeader

        Private usernameTokenField As UPSSecurityUsernameToken

        Private serviceAccessTokenField As UPSSecurityServiceAccessToken

        '''<remarks/>
        Public Property UsernameToken() As UPSSecurityUsernameToken
            Get
                Return Me.usernameTokenField
            End Get
            Set
                Me.usernameTokenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ServiceAccessToken() As UPSSecurityServiceAccessToken
            Get
                Return Me.serviceAccessTokenField
            End Get
            Set
                Me.serviceAccessTokenField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>
    Partial Public Class UPSSecurityUsernameToken

        Private usernameField As String

        Private passwordField As String

        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ResponseShipListAddressType

        Private townField As String

        Private cityField As String

        Private stateProvinceCodeField As String

        Private countryCodeField As String

        Private postcodePrimaryLowField As String

        Private postcodePrimaryHighField As String

        '''<remarks/>
        Public Property Town() As String
            Get
                Return Me.townField
            End Get
            Set
                Me.townField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property StateProvinceCode() As String
            Get
                Return Me.stateProvinceCodeField
            End Get
            Set
                Me.stateProvinceCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PostcodePrimaryLow() As String
            Get
                Return Me.postcodePrimaryLowField
            End Get
            Set
                Me.postcodePrimaryLowField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PostcodePrimaryHigh() As String
            Get
                Return Me.postcodePrimaryHighField
            End Get
            Set
                Me.postcodePrimaryHighField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class CandidateType

        Private addressField As ResponseShipListAddressType

        '''<remarks/>
        Public Property Address() As ResponseShipListAddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class CandidateResponseType

        Private shipFromListField() As CandidateType

        Private shipToListField() As CandidateType

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Candidate", IsNullable:=False)>
        Public Property ShipFromList() As CandidateType()
            Get
                Return Me.shipFromListField
            End Get
            Set
                Me.shipFromListField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Candidate", IsNullable:=False)>
        Public Property ShipToList() As CandidateType()
            Get
                Return Me.shipToListField
            End Get
            Set
                Me.shipToListField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class EstimatedArrivalType

        Private arrivalField As PickupType

        Private businessDaysInTransitField As String

        Private pickupField As PickupType

        Private dayOfWeekField As String

        Private customerCenterCutoffField As String

        Private delayCountField As String

        Private holidayCountField As String

        Private restDaysField As String

        Private totalTransitDaysField As String

        '''<remarks/>
        Public Property Arrival() As PickupType
            Get
                Return Me.arrivalField
            End Get
            Set
                Me.arrivalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property BusinessDaysInTransit() As String
            Get
                Return Me.businessDaysInTransitField
            End Get
            Set
                Me.businessDaysInTransitField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Pickup() As PickupType
            Get
                Return Me.pickupField
            End Get
            Set
                Me.pickupField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DayOfWeek() As String
            Get
                Return Me.dayOfWeekField
            End Get
            Set
                Me.dayOfWeekField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CustomerCenterCutoff() As String
            Get
                Return Me.customerCenterCutoffField
            End Get
            Set
                Me.customerCenterCutoffField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DelayCount() As String
            Get
                Return Me.delayCountField
            End Get
            Set
                Me.delayCountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property HolidayCount() As String
            Get
                Return Me.holidayCountField
            End Get
            Set
                Me.holidayCountField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property RestDays() As String
            Get
                Return Me.restDaysField
            End Get
            Set
                Me.restDaysField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalTransitDays() As String
            Get
                Return Me.totalTransitDaysField
            End Get
            Set
                Me.totalTransitDaysField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class PickupType

        Private dateField As String

        Private timeField As String

        '''<remarks/>
        Public Property [Date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Time() As String
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ServiceSummaryType

        Private serviceField As CodeDescriptionType

        Private guaranteedIndicatorField As String

        Private disclaimerField As String

        Private estimatedArrivalField As EstimatedArrivalType

        Private saturdayDeliveryField As String

        Private saturdayDeliveryDisclaimerField As String

        '''<remarks/>
        Public Property Service() As CodeDescriptionType
            Get
                Return Me.serviceField
            End Get
            Set
                Me.serviceField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property GuaranteedIndicator() As String
            Get
                Return Me.guaranteedIndicatorField
            End Get
            Set
                Me.guaranteedIndicatorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Disclaimer() As String
            Get
                Return Me.disclaimerField
            End Get
            Set
                Me.disclaimerField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property EstimatedArrival() As EstimatedArrivalType
            Get
                Return Me.estimatedArrivalField
            End Get
            Set
                Me.estimatedArrivalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SaturdayDelivery() As String
            Get
                Return Me.saturdayDeliveryField
            End Get
            Set
                Me.saturdayDeliveryField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SaturdayDeliveryDisclaimer() As String
            Get
                Return Me.saturdayDeliveryDisclaimerField
            End Get
            Set
                Me.saturdayDeliveryDisclaimerField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class CodeDescriptionType

        Private codeField As String

        Private descriptionField As String

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ResponseShipToType

        Private addressField As ResponseShipToAddressType

        '''<remarks/>
        Public Property Address() As ResponseShipToAddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ResponseShipToAddressType
        Inherits ResponseShipFromAddressType

        Private residentialAddressIndicatorField As String

        '''<remarks/>
        Public Property ResidentialAddressIndicator() As String
            Get
                Return Me.residentialAddressIndicatorField
            End Get
            Set
                Me.residentialAddressIndicatorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseShipToAddressType)),
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ResponseShipFromAddressType

        Private townField As String

        Private cityField As String

        Private stateProvinceCodeField As String

        Private countryCodeField As String

        Private countryField As String

        Private postalCodeField As String

        '''<remarks/>
        Public Property Town() As String
            Get
                Return Me.townField
            End Get
            Set
                Me.townField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property StateProvinceCode() As String
            Get
                Return Me.stateProvinceCodeField
            End Get
            Set
                Me.stateProvinceCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ResponseShipFromType

        Private addressField As ResponseShipFromAddressType

        '''<remarks/>
        Public Property Address() As ResponseShipFromAddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class TransitResponseType

        Private shipFromField As ResponseShipFromType

        Private shipToField As ResponseShipToType

        Private pickupDateField As String

        Private shipmentWeightField As ShipmentWeightType

        Private invoiceLineTotalField As InvoiceLineTotalType

        Private documentsOnlyIndicatorField As String

        Private maximumListSizeField As String

        Private serviceSummaryField() As ServiceSummaryType

        Private autoDutyCodeField As String

        Private disclaimerField As String

        '''<remarks/>
        Public Property ShipFrom() As ResponseShipFromType
            Get
                Return Me.shipFromField
            End Get
            Set
                Me.shipFromField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ShipTo() As ResponseShipToType
            Get
                Return Me.shipToField
            End Get
            Set
                Me.shipToField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PickupDate() As String
            Get
                Return Me.pickupDateField
            End Get
            Set
                Me.pickupDateField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ShipmentWeight() As ShipmentWeightType
            Get
                Return Me.shipmentWeightField
            End Get
            Set
                Me.shipmentWeightField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InvoiceLineTotal() As InvoiceLineTotalType
            Get
                Return Me.invoiceLineTotalField
            End Get
            Set
                Me.invoiceLineTotalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DocumentsOnlyIndicator() As String
            Get
                Return Me.documentsOnlyIndicatorField
            End Get
            Set
                Me.documentsOnlyIndicatorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MaximumListSize() As String
            Get
                Return Me.maximumListSizeField
            End Get
            Set
                Me.maximumListSizeField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ServiceSummary")>
        Public Property ServiceSummary() As ServiceSummaryType()
            Get
                Return Me.serviceSummaryField
            End Get
            Set
                Me.serviceSummaryField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property AutoDutyCode() As String
            Get
                Return Me.autoDutyCodeField
            End Get
            Set
                Me.autoDutyCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Disclaimer() As String
            Get
                Return Me.disclaimerField
            End Get
            Set
                Me.disclaimerField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class ShipmentWeightType

        Private unitOfMeasurementField As CodeDescriptionType

        Private weightField As String

        '''<remarks/>
        Public Property UnitOfMeasurement() As CodeDescriptionType
            Get
                Return Me.unitOfMeasurementField
            End Get
            Set
                Me.unitOfMeasurementField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Weight() As String
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class InvoiceLineTotalType

        Private currencyCodeField As String

        Private monetaryValueField As String

        '''<remarks/>
        Public Property CurrencyCode() As String
            Get
                Return Me.currencyCodeField
            End Get
            Set
                Me.currencyCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MonetaryValue() As String
            Get
                Return Me.monetaryValueField
            End Get
            Set
                Me.monetaryValueField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="CodeDescriptionType", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class CodeDescriptionType1

        Private codeField As String

        Private descriptionField As String

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class ResponseType

        Private responseStatusField As CodeDescriptionType1

        Private alertField() As CodeDescriptionType1

        Private transactionReferenceField As TransactionReferenceType

        '''<remarks/>
        Public Property ResponseStatus() As CodeDescriptionType1
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Alert")>
        Public Property Alert() As CodeDescriptionType1()
            Get
                Return Me.alertField
            End Get
            Set
                Me.alertField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class TransactionReferenceType

        Private customerContextField As String

        Private transactionIdentifierField As String

        '''<remarks/>
        Public Property CustomerContext() As String
            Get
                Return Me.customerContextField
            End Get
            Set
                Me.customerContextField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionIdentifier() As String
            Get
                Return Me.transactionIdentifierField
            End Get
            Set
                Me.transactionIdentifierField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class RequestShipToType

        Private addressField As RequestShipToAddressType

        '''<remarks/>
        Public Property Address() As RequestShipToAddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class RequestShipToAddressType
        Inherits RequestShipFromAddressType

        Private residentialAddressIndicatorField As String

        '''<remarks/>
        Public Property ResidentialAddressIndicator() As String
            Get
                Return Me.residentialAddressIndicatorField
            End Get
            Set
                Me.residentialAddressIndicatorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(RequestShipToAddressType)),
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class RequestShipFromAddressType

        Private townField As String

        Private cityField As String

        Private stateProvinceCodeField As String

        Private countryCodeField As String

        Private postalCodeField As String

        '''<remarks/>
        Public Property Town() As String
            Get
                Return Me.townField
            End Get
            Set
                Me.townField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property StateProvinceCode() As String
            Get
                Return Me.stateProvinceCodeField
            End Get
            Set
                Me.stateProvinceCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class RequestShipFromType

        Private addressField As RequestShipFromAddressType

        '''<remarks/>
        Public Property Address() As RequestShipFromAddressType
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class RequestType

        Private requestOptionField() As String

        Private transactionReferenceField As TransactionReferenceType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("RequestOption")>
        Public Property RequestOption() As String()
            Get
                Return Me.requestOptionField
            End Get
            Set
                Me.requestOptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>
    Partial Public Class UPSSecurityServiceAccessToken

        Private accessLicenseNumberField As String

        '''<remarks/>
        Public Property AccessLicenseNumber() As String
            Get
                Return Me.accessLicenseNumberField
            End Get
            Set
                Me.accessLicenseNumberField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class TimeInTransitRequest

        Private requestField As RequestType

        Private shipFromField As RequestShipFromType

        Private shipToField As RequestShipToType

        Private pickupField As PickupType

        Private shipmentWeightField As ShipmentWeightType

        Private totalPackagesInShipmentField As String

        Private invoiceLineTotalField As InvoiceLineTotalType

        Private documentsOnlyIndicatorField As String

        Private maximumListSizeField As String

        Private saturdayDeliveryInfoRequestIndicatorField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
        Public Property Request() As RequestType
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ShipFrom() As RequestShipFromType
            Get
                Return Me.shipFromField
            End Get
            Set
                Me.shipFromField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ShipTo() As RequestShipToType
            Get
                Return Me.shipToField
            End Get
            Set
                Me.shipToField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Pickup() As PickupType
            Get
                Return Me.pickupField
            End Get
            Set
                Me.pickupField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ShipmentWeight() As ShipmentWeightType
            Get
                Return Me.shipmentWeightField
            End Get
            Set
                Me.shipmentWeightField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalPackagesInShipment() As String
            Get
                Return Me.totalPackagesInShipmentField
            End Get
            Set
                Me.totalPackagesInShipmentField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property InvoiceLineTotal() As InvoiceLineTotalType
            Get
                Return Me.invoiceLineTotalField
            End Get
            Set
                Me.invoiceLineTotalField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DocumentsOnlyIndicator() As String
            Get
                Return Me.documentsOnlyIndicatorField
            End Get
            Set
                Me.documentsOnlyIndicatorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MaximumListSize() As String
            Get
                Return Me.maximumListSizeField
            End Get
            Set
                Me.maximumListSizeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SaturdayDeliveryInfoRequestIndicator() As String
            Get
                Return Me.saturdayDeliveryInfoRequestIndicatorField
            End Get
            Set
                Me.saturdayDeliveryInfoRequestIndicatorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/tnt/v1.0")>
    Partial Public Class TimeInTransitResponse

        Private responseField As ResponseType

        Private itemField As Object

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
        Public Property Response() As ResponseType
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CandidateResponse", GetType(CandidateResponseType)),
         System.Xml.Serialization.XmlElementAttribute("TransitResponse", GetType(TransitResponseType))>
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub ProcessTimeInTransitCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessTimeInTransitCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class ProcessTimeInTransitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As TimeInTransitResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), TimeInTransitResponse)
            End Get
        End Property
    End Class
End Namespace
