'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Net
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UPS_VoidWebReference

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="VoidBinding", [Namespace]:="http://www.ups.com/WSDL/XOLTWS/Void/v1.1")>
    Partial Public Class VoidService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private uPSSecurityValueField As UPSSecurity

        Private ProcessVoidOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.UPS_VoidWebReference_VoidService
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Property UPSSecurityValue() As UPSSecurity
            Get
                Return Me.uPSSecurityValueField
            End Get
            Set
                Me.uPSSecurityValueField = Value
            End Set
        End Property

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                            AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
                    MyBase.UseDefaultCredentials = False
                End If
                MyBase.Url = Value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = Value
                Me.useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        Public ReadOnly Property WebRequest() As Net.WebRequest
            Get
                Return GetWebRequest(New Uri(Me.Url))
            End Get
        End Property

        Public Property AccessToken As String

        Protected Overrides Function GetWebRequest(uri As Uri) As Net.WebRequest
            Dim req As HttpWebRequest = CType(MyBase.GetWebRequest(uri), HttpWebRequest)
            If Not String.IsNullOrWhiteSpace(AccessToken) Then
                req.Headers.Add(HttpRequestHeader.Authorization, "Bearer " & AccessToken)
            End If
            Return req
        End Function

        '''<remarks/>
        Public Event ProcessVoidCompleted As ProcessVoidCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("UPSSecurityValue"),
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://onlinetools.ups.com/webservices/VoidBinding/v1.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>
        Public Function ProcessVoid(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")> ByVal VoidShipmentRequest As VoidShipmentRequest) As <System.Xml.Serialization.XmlElementAttribute("VoidShipmentResponse", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")> VoidShipmentResponse
            Dim results() As Object = Me.Invoke("ProcessVoid", New Object() {VoidShipmentRequest})
            Return CType(results(0), VoidShipmentResponse)
        End Function

        '''<remarks/>
        Public Overloads Sub ProcessVoidAsync(ByVal VoidShipmentRequest As VoidShipmentRequest)
            Me.ProcessVoidAsync(VoidShipmentRequest, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub ProcessVoidAsync(ByVal VoidShipmentRequest As VoidShipmentRequest, ByVal userState As Object)
            If (Me.ProcessVoidOperationCompleted Is Nothing) Then
                Me.ProcessVoidOperationCompleted = AddressOf Me.OnProcessVoidOperationCompleted
            End If
            Me.InvokeAsync("ProcessVoid", New Object() {VoidShipmentRequest}, Me.ProcessVoidOperationCompleted, userState)
        End Sub

        Private Sub OnProcessVoidOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessVoidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessVoidCompleted(Me, New ProcessVoidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                Return False
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024) _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return True
            End If
            Return False
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0"),
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", IsNullable:=False)>
    Partial Public Class UPSSecurity
        Inherits System.Web.Services.Protocols.SoapHeader

        Private usernameTokenField As UPSSecurityUsernameToken

        Private serviceAccessTokenField As UPSSecurityServiceAccessToken

        '''<remarks/>
        Public Property UsernameToken() As UPSSecurityUsernameToken
            Get
                Return Me.usernameTokenField
            End Get
            Set
                Me.usernameTokenField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property ServiceAccessToken() As UPSSecurityServiceAccessToken
            Get
                Return Me.serviceAccessTokenField
            End Get
            Set
                Me.serviceAccessTokenField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>
    Partial Public Class UPSSecurityUsernameToken

        Private usernameField As String

        Private passwordField As String

        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class PackageLevelResult

        Private trackingNumberField As String

        Private statusField As CodeDescriptionType1

        '''<remarks/>
        Public Property TrackingNumber() As String
            Get
                Return Me.trackingNumberField
            End Get
            Set
                Me.trackingNumberField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Status() As CodeDescriptionType1
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="CodeDescriptionType", [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class CodeDescriptionType1

        Private codeField As String

        Private descriptionField As String

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class CodeDescriptionType

        Private codeField As String

        Private descriptionField As String

        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class ResponseType

        Private responseStatusField As CodeDescriptionType

        Private alertField() As CodeDescriptionType

        Private transactionReferenceField As TransactionReferenceType

        '''<remarks/>
        Public Property ResponseStatus() As CodeDescriptionType
            Get
                Return Me.responseStatusField
            End Get
            Set
                Me.responseStatusField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Alert")>
        Public Property Alert() As CodeDescriptionType()
            Get
                Return Me.alertField
            End Get
            Set
                Me.alertField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class TransactionReferenceType

        Private customerContextField As String

        Private transactionIdentifierField As String

        '''<remarks/>
        Public Property CustomerContext() As String
            Get
                Return Me.customerContextField
            End Get
            Set
                Me.customerContextField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionIdentifier() As String
            Get
                Return Me.transactionIdentifierField
            End Get
            Set
                Me.transactionIdentifierField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
    Partial Public Class RequestType

        Private requestOptionField() As String

        Private transactionReferenceField As TransactionReferenceType

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("RequestOption")>
        Public Property RequestOption() As String()
            Get
                Return Me.requestOptionField
            End Get
            Set
                Me.requestOptionField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TransactionReference() As TransactionReferenceType
            Get
                Return Me.transactionReferenceField
            End Get
            Set
                Me.transactionReferenceField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0")>
    Partial Public Class UPSSecurityServiceAccessToken

        Private accessLicenseNumberField As String

        '''<remarks/>
        Public Property AccessLicenseNumber() As String
            Get
                Return Me.accessLicenseNumberField
            End Get
            Set
                Me.accessLicenseNumberField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class VoidShipmentRequest

        Private requestField As RequestType

        Private voidShipmentField As VoidShipmentRequestVoidShipment

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
        Public Property Request() As RequestType
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property VoidShipment() As VoidShipmentRequestVoidShipment
            Get
                Return Me.voidShipmentField
            End Get
            Set
                Me.voidShipmentField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class VoidShipmentRequestVoidShipment

        Private shipmentIdentificationNumberField As String

        Private trackingNumberField() As String

        '''<remarks/>
        Public Property ShipmentIdentificationNumber() As String
            Get
                Return Me.shipmentIdentificationNumberField
            End Get
            Set
                Me.shipmentIdentificationNumberField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("TrackingNumber")>
        Public Property TrackingNumber() As String()
            Get
                Return Me.trackingNumberField
            End Get
            Set
                Me.trackingNumberField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class VoidShipmentResponse

        Private responseField As ResponseType

        Private summaryResultField As VoidShipmentResponseSummaryResult

        Private packageLevelResultField() As PackageLevelResult

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0")>
        Public Property Response() As ResponseType
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property SummaryResult() As VoidShipmentResponseSummaryResult
            Get
                Return Me.summaryResultField
            End Get
            Set
                Me.summaryResultField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PackageLevelResult")>
        Public Property PackageLevelResult() As PackageLevelResult()
            Get
                Return Me.packageLevelResultField
            End Get
            Set
                Me.packageLevelResultField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),
     System.SerializableAttribute(),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.ups.com/XMLSchema/XOLTWS/Void/v1.1")>
    Partial Public Class VoidShipmentResponseSummaryResult

        Private statusField As CodeDescriptionType1

        '''<remarks/>
        Public Property Status() As CodeDescriptionType1
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub ProcessVoidCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessVoidCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class ProcessVoidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As VoidShipmentResponse
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), VoidShipmentResponse)
            End Get
        End Property
    End Class
End Namespace
