'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.8.3928.0.
'
Namespace DHL_DCTReq
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.dhl.com", IsNullable:=false)>  _
    Partial Public Class DCTRequest
        
        Private itemField As Object

        Private schemaVersionField As Decimal

        <XmlNamespaceDeclarations>
        Public xmlns As New XmlSerializerNamespaces

        Public Sub New()
            MyBase.New
            Me.schemaVersionField = CType(2.0, Decimal)
            Me.xmlns.Add("p", "http://www.dhl.com")
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("GetCapability", GetType(DCTRequestGetCapability), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlElementAttribute("GetQuote", GetType(DCTRequestGetQuote), Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>
        Public Property schemaVersion() As String
            Get
                Return Me.schemaVersionField.ToString("0.0") ' needs to send trailing 0
            End Get
            Set
                Me.schemaVersionField = CType(Value, Decimal)
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class DCTRequestGetCapability
        
        Private requestField As Request
        
        Private fromField As DCTFrom
        
        Private bkgDetailsField As BkgDetailsType
        
        Private toField As DCTTo
        
        Private dutiableField As DCTDutiable
        
        Private genReqField As GenReq
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Request() As Request
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property From() As DCTFrom
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BkgDetails() As BkgDetailsType
            Get
                Return Me.bkgDetailsField
            End Get
            Set
                Me.bkgDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [To]() As DCTTo
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dutiable() As DCTDutiable
            Get
                Return Me.dutiableField
            End Get
            Set
                Me.dutiableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GenReq() As GenReq
            Get
                Return Me.genReqField
            End Get
            Set
                Me.genReqField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/datatypes_global")>  _
    Partial Public Class Request
        
        Private serviceHeaderField As ServiceHeader
        
        Private metaDataField As MetaData
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ServiceHeader() As ServiceHeader
            Get
                Return Me.serviceHeaderField
            End Get
            Set
                Me.serviceHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MetaData() As MetaData
            Get
                Return Me.metaDataField
            End Get
            Set
                Me.metaDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/datatypes_global")>  _
    Partial Public Class ServiceHeader
        
        Private messageTimeField As Date
        
        Private gMTOffsetField As String
        
        Private messageReferenceField As String
        
        Private siteIDField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MessageTime() As Date
            Get
                Return Me.messageTimeField
            End Get
            Set
                Me.messageTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GMTOffset() As String
            Get
                Return Me.gMTOffsetField
            End Get
            Set
                Me.gMTOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MessageReference() As String
            Get
                Return Me.messageReferenceField
            End Get
            Set
                Me.messageReferenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SiteID() As String
            Get
                Return Me.siteIDField
            End Get
            Set
                Me.siteIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class GenReq
        
        Private oSINFOField As GenReqOSINFO
        
        Private oSINFOFieldSpecified As Boolean
        
        Private nXTPUField As GenReqNXTPU
        
        Private nXTPUFieldSpecified As Boolean
        
        Private fCNTWTYCDField As GenReqFCNTWTYCD
        
        Private fCNTWTYCDFieldSpecified As Boolean
        
        Private cUSTAGRINDField As GenReqCUSTAGRIND
        
        Private cUSTAGRINDFieldSpecified As Boolean
        
        Private vLDTRT_DDField As GenReqVLDTRT_DD
        
        Private vLDTRT_DDFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OSINFO() As GenReqOSINFO
            Get
                Return Me.oSINFOField
            End Get
            Set
                Me.oSINFOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OSINFOSpecified() As Boolean
            Get
                Return Me.oSINFOFieldSpecified
            End Get
            Set
                Me.oSINFOFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NXTPU() As GenReqNXTPU
            Get
                Return Me.nXTPUField
            End Get
            Set
                Me.nXTPUField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NXTPUSpecified() As Boolean
            Get
                Return Me.nXTPUFieldSpecified
            End Get
            Set
                Me.nXTPUFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FCNTWTYCD() As GenReqFCNTWTYCD
            Get
                Return Me.fCNTWTYCDField
            End Get
            Set
                Me.fCNTWTYCDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FCNTWTYCDSpecified() As Boolean
            Get
                Return Me.fCNTWTYCDFieldSpecified
            End Get
            Set
                Me.fCNTWTYCDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CUSTAGRIND() As GenReqCUSTAGRIND
            Get
                Return Me.cUSTAGRINDField
            End Get
            Set
                Me.cUSTAGRINDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CUSTAGRINDSpecified() As Boolean
            Get
                Return Me.cUSTAGRINDFieldSpecified
            End Get
            Set
                Me.cUSTAGRINDFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VLDTRT_DD() As GenReqVLDTRT_DD
            Get
                Return Me.vLDTRT_DDField
            End Get
            Set
                Me.vLDTRT_DDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property VLDTRT_DDSpecified() As Boolean
            Get
                Return Me.vLDTRT_DDFieldSpecified
            End Get
            Set
                Me.vLDTRT_DDFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum GenReqOSINFO
        
        '''<remarks/>
        Y
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum GenReqNXTPU
        
        '''<remarks/>
        Y
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum GenReqFCNTWTYCD
        
        '''<remarks/>
        DD
        
        '''<remarks/>
        TD
        
        '''<remarks/>
        AL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum GenReqCUSTAGRIND
        
        '''<remarks/>
        Y
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum GenReqVLDTRT_DD
        
        '''<remarks/>
        Y
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class DCTDutiable
        
        Private declaredCurrencyField As String
        
        Private declaredValueField As Single
        
        Private declaredValueFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DeclaredCurrency() As String
            Get
                Return Me.declaredCurrencyField
            End Get
            Set
                Me.declaredCurrencyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DeclaredValue() As Single
            Get
                Return Me.declaredValueField
            End Get
            Set
                Me.declaredValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DeclaredValueSpecified() As Boolean
            Get
                Return Me.declaredValueFieldSpecified
            End Get
            Set
                Me.declaredValueFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class DCTTo
        
        Private countryCodeField As String
        
        Private postalcodeField As String
        
        Private cityField As String
        
        Private suburbField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Postalcode() As String
            Get
                Return Me.postalcodeField
            End Get
            Set
                Me.postalcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Suburb() As String
            Get
                Return Me.suburbField
            End Get
            Set
                Me.suburbField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class QtdShpExChrgType
        
        Private specialServiceTypeField As String
        
        Private localSpecialServiceTypeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SpecialServiceType() As String
            Get
                Return Me.specialServiceTypeField
            End Get
            Set
                Me.specialServiceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LocalSpecialServiceType() As String
            Get
                Return Me.localSpecialServiceTypeField
            End Get
            Set
                Me.localSpecialServiceTypeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class QtdShpType
        
        Private globalProductCodeField As String
        
        Private localProductCodeField As String
        
        Private qtdShpExChrgField() As QtdShpExChrgType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GlobalProductCode() As String
            Get
                Return Me.globalProductCodeField
            End Get
            Set
                Me.globalProductCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LocalProductCode() As String
            Get
                Return Me.localProductCodeField
            End Get
            Set
                Me.localProductCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("QtdShpExChrg", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property QtdShpExChrg() As QtdShpExChrgType()
            Get
                Return Me.qtdShpExChrgField
            End Get
            Set
                Me.qtdShpExChrgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class PieceType
        
        Private pieceIDField As String
        
        Private packageTypeCodeField As PieceTypePackageTypeCode
        
        Private heightField As Decimal
        
        Private heightFieldSpecified As Boolean
        
        Private depthField As Decimal
        
        Private depthFieldSpecified As Boolean
        
        Private widthField As Decimal
        
        Private widthFieldSpecified As Boolean
        
        Private weightField As Decimal
        
        Public Sub New()
            MyBase.New
            Me.packageTypeCodeField = PieceTypePackageTypeCode.BOX
        End Sub
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PieceID() As String
            Get
                Return Me.pieceIDField
            End Get
            Set
                Me.pieceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.ComponentModel.DefaultValueAttribute(PieceTypePackageTypeCode.BOX)>  _
        Public Property PackageTypeCode() As PieceTypePackageTypeCode
            Get
                Return Me.packageTypeCodeField
            End Get
            Set
                Me.packageTypeCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Height() As Decimal
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeightSpecified() As Boolean
            Get
                Return Me.heightFieldSpecified
            End Get
            Set
                Me.heightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Depth() As Decimal
            Get
                Return Me.depthField
            End Get
            Set
                Me.depthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DepthSpecified() As Boolean
            Get
                Return Me.depthFieldSpecified
            End Get
            Set
                Me.depthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Width() As Decimal
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WidthSpecified() As Boolean
            Get
                Return Me.widthFieldSpecified
            End Get
            Set
                Me.widthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Weight() As Decimal
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum PieceTypePackageTypeCode
        
        '''<remarks/>
        FLY
        
        '''<remarks/>
        COY
        
        '''<remarks/>
        NCY
        
        '''<remarks/>
        PAL
        
        '''<remarks/>
        DBL
        
        '''<remarks/>
        BOX
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class BkgDetailsType
        
        Private paymentCountryCodeField As String
        
        Private dateField As Date
        
        Private readyTimeField As String
        
        Private readyTimeGMTOffsetField As String
        
        Private dimensionUnitField As BkgDetailsTypeDimensionUnit
        
        Private weightUnitField As BkgDetailsTypeWeightUnit
        
        Private numberOfPiecesField As String
        
        Private shipmentWeightField As Decimal
        
        Private shipmentWeightFieldSpecified As Boolean
        
        Private volumeField As Decimal
        
        Private volumeFieldSpecified As Boolean
        
        Private maxPieceWeightField As Decimal
        
        Private maxPieceWeightFieldSpecified As Boolean
        
        Private maxPieceHeightField As Decimal
        
        Private maxPieceHeightFieldSpecified As Boolean
        
        Private maxPieceDepthField As Decimal
        
        Private maxPieceDepthFieldSpecified As Boolean
        
        Private maxPieceWidthField As Decimal
        
        Private maxPieceWidthFieldSpecified As Boolean
        
        Private piecesField() As PieceType
        
        Private paymentAccountNumberField As String
        
        Private isDutiableField As BkgDetailsTypeIsDutiable
        
        Private isDutiableFieldSpecified As Boolean
        
        Private networkTypeCodeField As BkgDetailsTypeNetworkTypeCode
        
        Private networkTypeCodeFieldSpecified As Boolean
        
        Private qtdShpField() As QtdShpType
        
        Private insuredValueField As Decimal
        
        Private insuredValueFieldSpecified As Boolean
        
        Private insuredCurrencyField As String
        
        Private paymentTypeField As BkgDetailsTypePaymentType
        
        Private paymentTypeFieldSpecified As Boolean
        
        Private acctPickupCloseTimeField As Date
        
        Private acctPickupCloseTimeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PaymentCountryCode() As String
            Get
                Return Me.paymentCountryCodeField
            End Get
            Set
                Me.paymentCountryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date")>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="duration")>  _
        Public Property ReadyTime() As String
            Get
                Return Me.readyTimeField
            End Get
            Set
                Me.readyTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ReadyTimeGMTOffset() As String
            Get
                Return Me.readyTimeGMTOffsetField
            End Get
            Set
                Me.readyTimeGMTOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DimensionUnit() As BkgDetailsTypeDimensionUnit
            Get
                Return Me.dimensionUnitField
            End Get
            Set
                Me.dimensionUnitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WeightUnit() As BkgDetailsTypeWeightUnit
            Get
                Return Me.weightUnitField
            End Get
            Set
                Me.weightUnitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="positiveInteger")>  _
        Public Property NumberOfPieces() As String
            Get
                Return Me.numberOfPiecesField
            End Get
            Set
                Me.numberOfPiecesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ShipmentWeight() As Decimal
            Get
                Return Me.shipmentWeightField
            End Get
            Set
                Me.shipmentWeightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ShipmentWeightSpecified() As Boolean
            Get
                Return Me.shipmentWeightFieldSpecified
            End Get
            Set
                Me.shipmentWeightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Volume() As Decimal
            Get
                Return Me.volumeField
            End Get
            Set
                Me.volumeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property VolumeSpecified() As Boolean
            Get
                Return Me.volumeFieldSpecified
            End Get
            Set
                Me.volumeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MaxPieceWeight() As Decimal
            Get
                Return Me.maxPieceWeightField
            End Get
            Set
                Me.maxPieceWeightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxPieceWeightSpecified() As Boolean
            Get
                Return Me.maxPieceWeightFieldSpecified
            End Get
            Set
                Me.maxPieceWeightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MaxPieceHeight() As Decimal
            Get
                Return Me.maxPieceHeightField
            End Get
            Set
                Me.maxPieceHeightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxPieceHeightSpecified() As Boolean
            Get
                Return Me.maxPieceHeightFieldSpecified
            End Get
            Set
                Me.maxPieceHeightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MaxPieceDepth() As Decimal
            Get
                Return Me.maxPieceDepthField
            End Get
            Set
                Me.maxPieceDepthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxPieceDepthSpecified() As Boolean
            Get
                Return Me.maxPieceDepthFieldSpecified
            End Get
            Set
                Me.maxPieceDepthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MaxPieceWidth() As Decimal
            Get
                Return Me.maxPieceWidthField
            End Get
            Set
                Me.maxPieceWidthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MaxPieceWidthSpecified() As Boolean
            Get
                Return Me.maxPieceWidthFieldSpecified
            End Get
            Set
                Me.maxPieceWidthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Piece", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Pieces() As PieceType()
            Get
                Return Me.piecesField
            End Get
            Set
                Me.piecesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PaymentAccountNumber() As String
            Get
                Return Me.paymentAccountNumberField
            End Get
            Set
                Me.paymentAccountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IsDutiable() As BkgDetailsTypeIsDutiable
            Get
                Return Me.isDutiableField
            End Get
            Set
                Me.isDutiableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IsDutiableSpecified() As Boolean
            Get
                Return Me.isDutiableFieldSpecified
            End Get
            Set
                Me.isDutiableFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NetworkTypeCode() As BkgDetailsTypeNetworkTypeCode
            Get
                Return Me.networkTypeCodeField
            End Get
            Set
                Me.networkTypeCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NetworkTypeCodeSpecified() As Boolean
            Get
                Return Me.networkTypeCodeFieldSpecified
            End Get
            Set
                Me.networkTypeCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("QtdShp", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property QtdShp() As QtdShpType()
            Get
                Return Me.qtdShpField
            End Get
            Set
                Me.qtdShpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property InsuredValue() As Decimal
            Get
                Return Me.insuredValueField
            End Get
            Set
                Me.insuredValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property InsuredValueSpecified() As Boolean
            Get
                Return Me.insuredValueFieldSpecified
            End Get
            Set
                Me.insuredValueFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property InsuredCurrency() As String
            Get
                Return Me.insuredCurrencyField
            End Get
            Set
                Me.insuredCurrencyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PaymentType() As BkgDetailsTypePaymentType
            Get
                Return Me.paymentTypeField
            End Get
            Set
                Me.paymentTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PaymentTypeSpecified() As Boolean
            Get
                Return Me.paymentTypeFieldSpecified
            End Get
            Set
                Me.paymentTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property AcctPickupCloseTime() As Date
            Get
                Return Me.acctPickupCloseTimeField
            End Get
            Set
                Me.acctPickupCloseTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AcctPickupCloseTimeSpecified() As Boolean
            Get
                Return Me.acctPickupCloseTimeFieldSpecified
            End Get
            Set
                Me.acctPickupCloseTimeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum BkgDetailsTypeDimensionUnit
        
        '''<remarks/>
        [IN]
        
        '''<remarks/>
        CM
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum BkgDetailsTypeWeightUnit
        
        '''<remarks/>
        KG
        
        '''<remarks/>
        LB
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum BkgDetailsTypeIsDutiable
        
        '''<remarks/>
        Y
        
        '''<remarks/>
        N
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum BkgDetailsTypeNetworkTypeCode
        
        '''<remarks/>
        DD
        
        '''<remarks/>
        TD
        
        '''<remarks/>
        AL
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Public Enum BkgDetailsTypePaymentType
        
        '''<remarks/>
        D
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/DCTRequestdatatypes")>  _
    Partial Public Class DCTFrom
        
        Private countryCodeField As String
        
        Private postalcodeField As String
        
        Private cityField As String
        
        Private suburbField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Postalcode() As String
            Get
                Return Me.postalcodeField
            End Get
            Set
                Me.postalcodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Suburb() As String
            Get
                Return Me.suburbField
            End Get
            Set
                Me.suburbField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.dhl.com/datatypes_global")>  _
    Partial Public Class MetaData
        
        Private softwareNameField As String
        
        Private softwareVersionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SoftwareName() As String
            Get
                Return Me.softwareNameField
            End Get
            Set
                Me.softwareNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SoftwareVersion() As String
            Get
                Return Me.softwareVersionField
            End Get
            Set
                Me.softwareVersionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _
    Partial Public Class DCTRequestGetQuote
        
        Private requestField As Request
        
        Private fromField As DCTFrom
        
        Private bkgDetailsField As BkgDetailsType
        
        Private toField As DCTTo
        
        Private dutiableField As DCTDutiable
        
        Private genReqField As GenReq
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Request() As Request
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property From() As DCTFrom
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BkgDetails() As BkgDetailsType
            Get
                Return Me.bkgDetailsField
            End Get
            Set
                Me.bkgDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property [To]() As DCTTo
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dutiable() As DCTDutiable
            Get
                Return Me.dutiableField
            End Get
            Set
                Me.dutiableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property GenReq() As GenReq
            Get
                Return Me.genReqField
            End Get
            Set
                Me.genReqField = value
            End Set
        End Property
    End Class
End Namespace
