'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace FedEx_RegistrationService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="RegistrationServiceSoapBinding", [Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class RegistrationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private registerWebUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private versionCaptureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private subscriptionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SHIPRITE.MySettings.Default.FedEx_RegistrationService_RegistrationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event registerWebUserCompleted As registerWebUserCompletedEventHandler
        
        '''<remarks/>
        Public Event versionCaptureCompleted As versionCaptureCompletedEventHandler
        
        '''<remarks/>
        Public Event subscriptionCompleted As subscriptionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/registration/v7/registerWebUser", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function registerWebUser(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://fedex.com/ws/registration/v7")> ByVal RegisterWebUserRequest As RegisterWebUserRequest) As <System.Xml.Serialization.XmlElementAttribute("RegisterWebUserReply", [Namespace]:="http://fedex.com/ws/registration/v7")> RegisterWebUserReply
            Dim results() As Object = Me.Invoke("registerWebUser", New Object() {RegisterWebUserRequest})
            Return CType(results(0),RegisterWebUserReply)
        End Function
        
        '''<remarks/>
        Public Overloads Sub registerWebUserAsync(ByVal RegisterWebUserRequest As RegisterWebUserRequest)
            Me.registerWebUserAsync(RegisterWebUserRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub registerWebUserAsync(ByVal RegisterWebUserRequest As RegisterWebUserRequest, ByVal userState As Object)
            If (Me.registerWebUserOperationCompleted Is Nothing) Then
                Me.registerWebUserOperationCompleted = AddressOf Me.OnregisterWebUserOperationCompleted
            End If
            Me.InvokeAsync("registerWebUser", New Object() {RegisterWebUserRequest}, Me.registerWebUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnregisterWebUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.registerWebUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent registerWebUserCompleted(Me, New registerWebUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/registration/v7/versionCapture", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function versionCapture(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://fedex.com/ws/registration/v7")> ByVal VersionCaptureRequest As VersionCaptureRequest) As <System.Xml.Serialization.XmlElementAttribute("VersionCaptureReply", [Namespace]:="http://fedex.com/ws/registration/v7")> VersionCaptureReply
            Dim results() As Object = Me.Invoke("versionCapture", New Object() {VersionCaptureRequest})
            Return CType(results(0),VersionCaptureReply)
        End Function
        
        '''<remarks/>
        Public Overloads Sub versionCaptureAsync(ByVal VersionCaptureRequest As VersionCaptureRequest)
            Me.versionCaptureAsync(VersionCaptureRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub versionCaptureAsync(ByVal VersionCaptureRequest As VersionCaptureRequest, ByVal userState As Object)
            If (Me.versionCaptureOperationCompleted Is Nothing) Then
                Me.versionCaptureOperationCompleted = AddressOf Me.OnversionCaptureOperationCompleted
            End If
            Me.InvokeAsync("versionCapture", New Object() {VersionCaptureRequest}, Me.versionCaptureOperationCompleted, userState)
        End Sub
        
        Private Sub OnversionCaptureOperationCompleted(ByVal arg As Object)
            If (Not (Me.versionCaptureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent versionCaptureCompleted(Me, New versionCaptureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/registration/v7/subscription", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function subscription(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://fedex.com/ws/registration/v7")> ByVal SubscriptionRequest As SubscriptionRequest) As <System.Xml.Serialization.XmlElementAttribute("SubscriptionReply", [Namespace]:="http://fedex.com/ws/registration/v7")> SubscriptionReply
            Dim results() As Object = Me.Invoke("subscription", New Object() {SubscriptionRequest})
            Return CType(results(0),SubscriptionReply)
        End Function
        
        '''<remarks/>
        Public Overloads Sub subscriptionAsync(ByVal SubscriptionRequest As SubscriptionRequest)
            Me.subscriptionAsync(SubscriptionRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub subscriptionAsync(ByVal SubscriptionRequest As SubscriptionRequest, ByVal userState As Object)
            If (Me.subscriptionOperationCompleted Is Nothing) Then
                Me.subscriptionOperationCompleted = AddressOf Me.OnsubscriptionOperationCompleted
            End If
            Me.InvokeAsync("subscription", New Object() {SubscriptionRequest}, Me.subscriptionOperationCompleted, userState)
        End Sub
        
        Private Sub OnsubscriptionOperationCompleted(ByVal arg As Object)
            If (Not (Me.subscriptionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent subscriptionCompleted(Me, New subscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class RegisterWebUserRequest
        
        Private webAuthenticationDetailField As WebAuthenticationDetail
        
        Private clientDetailField As ClientDetail
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private parentCredentialField As WebAuthenticationCredential
        
        Private categoriesField() As WebServiceCategoryType
        
        Private shippingAddressField As Address
        
        Private userContactAndAddressField As ParsedContactAndAddress
        
        Private secondaryEmailField As String
        
        '''<remarks/>
        Public Property WebAuthenticationDetail() As WebAuthenticationDetail
            Get
                Return Me.webAuthenticationDetailField
            End Get
            Set
                Me.webAuthenticationDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientDetail() As ClientDetail
            Get
                Return Me.clientDetailField
            End Get
            Set
                Me.clientDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentCredential() As WebAuthenticationCredential
            Get
                Return Me.parentCredentialField
            End Get
            Set
                Me.parentCredentialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Categories")>  _
        Public Property Categories() As WebServiceCategoryType()
            Get
                Return Me.categoriesField
            End Get
            Set
                Me.categoriesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShippingAddress() As Address
            Get
                Return Me.shippingAddressField
            End Get
            Set
                Me.shippingAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserContactAndAddress() As ParsedContactAndAddress
            Get
                Return Me.userContactAndAddressField
            End Get
            Set
                Me.userContactAndAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecondaryEmail() As String
            Get
                Return Me.secondaryEmailField
            End Get
            Set
                Me.secondaryEmailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class WebAuthenticationDetail
        
        Private parentCredentialField As WebAuthenticationCredential
        
        Private userCredentialField As WebAuthenticationCredential
        
        '''<remarks/>
        Public Property ParentCredential() As WebAuthenticationCredential
            Get
                Return Me.parentCredentialField
            End Get
            Set
                Me.parentCredentialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserCredential() As WebAuthenticationCredential
            Get
                Return Me.userCredentialField
            End Get
            Set
                Me.userCredentialField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class WebAuthenticationCredential
        
        Private keyField As String
        
        Private passwordField As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class MeterDetail
        
        Private meterNumberField As String
        
        Private groundShipperNumberField As String
        
        Private epdiCodeField As String
        
        Private reconcileTimeField As Date
        
        Private reconcileTimeFieldSpecified As Boolean
        
        Private groundTrackingNumberStartField As String
        
        Private groundTrackingNumberEndField As String
        
        '''<remarks/>
        Public Property MeterNumber() As String
            Get
                Return Me.meterNumberField
            End Get
            Set
                Me.meterNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroundShipperNumber() As String
            Get
                Return Me.groundShipperNumberField
            End Get
            Set
                Me.groundShipperNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EpdiCode() As String
            Get
                Return Me.epdiCodeField
            End Get
            Set
                Me.epdiCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="time")>  _
        Public Property ReconcileTime() As Date
            Get
                Return Me.reconcileTimeField
            End Get
            Set
                Me.reconcileTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ReconcileTimeSpecified() As Boolean
            Get
                Return Me.reconcileTimeFieldSpecified
            End Get
            Set
                Me.reconcileTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroundTrackingNumberStart() As String
            Get
                Return Me.groundTrackingNumberStartField
            End Get
            Set
                Me.groundTrackingNumberStartField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroundTrackingNumberEnd() As String
            Get
                Return Me.groundTrackingNumberEndField
            End Get
            Set
                Me.groundTrackingNumberEndField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class SubscriptionReply
        
        Private highestSeverityField As NotificationSeverityType
        
        Private highestSeverityFieldSpecified As Boolean
        
        Private notificationsField() As Notification
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private meterDetailField As MeterDetail
        
        Private registeredServicesField() As SubscriptionServiceType
        
        '''<remarks/>
        Public Property HighestSeverity() As NotificationSeverityType
            Get
                Return Me.highestSeverityField
            End Get
            Set
                Me.highestSeverityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HighestSeveritySpecified() As Boolean
            Get
                Return Me.highestSeverityFieldSpecified
            End Get
            Set
                Me.highestSeverityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Notifications")>  _
        Public Property Notifications() As Notification()
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MeterDetail() As MeterDetail
            Get
                Return Me.meterDetailField
            End Get
            Set
                Me.meterDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("RegisteredServices")>  _
        Public Property RegisteredServices() As SubscriptionServiceType()
            Get
                Return Me.registeredServicesField
            End Get
            Set
                Me.registeredServicesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Public Enum NotificationSeverityType
        
        '''<remarks/>
        [ERROR]
        
        '''<remarks/>
        FAILURE
        
        '''<remarks/>
        NOTE
        
        '''<remarks/>
        SUCCESS
        
        '''<remarks/>
        WARNING
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class Notification
        
        Private severityField As NotificationSeverityType
        
        Private severityFieldSpecified As Boolean
        
        Private sourceField As String
        
        Private codeField As String
        
        Private messageField As String
        
        Private localizedMessageField As String
        
        Private messageParametersField() As NotificationParameter
        
        '''<remarks/>
        Public Property Severity() As NotificationSeverityType
            Get
                Return Me.severityField
            End Get
            Set
                Me.severityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SeveritySpecified() As Boolean
            Get
                Return Me.severityFieldSpecified
            End Get
            Set
                Me.severityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocalizedMessage() As String
            Get
                Return Me.localizedMessageField
            End Get
            Set
                Me.localizedMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MessageParameters")>  _
        Public Property MessageParameters() As NotificationParameter()
            Get
                Return Me.messageParametersField
            End Get
            Set
                Me.messageParametersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class NotificationParameter
        
        Private idField As String
        
        Private valueField As String
        
        '''<remarks/>
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class TransactionDetail
        
        Private customerTransactionIdField As String
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property CustomerTransactionId() As String
            Get
                Return Me.customerTransactionIdField
            End Get
            Set
                Me.customerTransactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class Localization
        
        Private languageCodeField As String
        
        Private localeCodeField As String
        
        '''<remarks/>
        Public Property LanguageCode() As String
            Get
                Return Me.languageCodeField
            End Get
            Set
                Me.languageCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LocaleCode() As String
            Get
                Return Me.localeCodeField
            End Get
            Set
                Me.localeCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class VersionId
        
        Private serviceIdField As String
        
        Private majorField As Integer
        
        Private intermediateField As Integer
        
        Private minorField As Integer
        
        Public Sub New()
            MyBase.New
            Me.serviceIdField = "fcas"
            Me.majorField = 7
            Me.intermediateField = 0
            Me.minorField = 0
        End Sub
        
        '''<remarks/>
        Public Property ServiceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Major() As Integer
            Get
                Return Me.majorField
            End Get
            Set
                Me.majorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Intermediate() As Integer
            Get
                Return Me.intermediateField
            End Get
            Set
                Me.intermediateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Minor() As Integer
            Get
                Return Me.minorField
            End Get
            Set
                Me.minorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Public Enum SubscriptionServiceType
        
        '''<remarks/>
        EXPRESS_SHIPPING
        
        '''<remarks/>
        GROUND_SHIPPING
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class Contact
        
        Private personNameField As String
        
        Private companyNameField As String
        
        Private phoneNumberField As String
        
        Private phoneExtensionField As String
        
        Private tollFreePhoneNumberField As String
        
        Private pagerNumberField As String
        
        Private faxNumberField As String
        
        Private eMailAddressField As String
        
        '''<remarks/>
        Public Property PersonName() As String
            Get
                Return Me.personNameField
            End Get
            Set
                Me.personNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneExtension() As String
            Get
                Return Me.phoneExtensionField
            End Get
            Set
                Me.phoneExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TollFreePhoneNumber() As String
            Get
                Return Me.tollFreePhoneNumberField
            End Get
            Set
                Me.tollFreePhoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PagerNumber() As String
            Get
                Return Me.pagerNumberField
            End Get
            Set
                Me.pagerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FaxNumber() As String
            Get
                Return Me.faxNumberField
            End Get
            Set
                Me.faxNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMailAddress() As String
            Get
                Return Me.eMailAddressField
            End Get
            Set
                Me.eMailAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class Party
        
        Private accountNumberField As String
        
        Private contactField As Contact
        
        Private addressField As Address
        
        '''<remarks/>
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Contact() As Contact
            Get
                Return Me.contactField
            End Get
            Set
                Me.contactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class Address
        
        Private streetLinesField() As String
        
        Private cityField As String
        
        Private stateOrProvinceCodeField As String
        
        Private postalCodeField As String
        
        Private countryCodeField As String
        
        Private countryNameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("StreetLines")>  _
        Public Property StreetLines() As String()
            Get
                Return Me.streetLinesField
            End Get
            Set
                Me.streetLinesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StateOrProvinceCode() As String
            Get
                Return Me.stateOrProvinceCodeField
            End Get
            Set
                Me.stateOrProvinceCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryCode() As String
            Get
                Return Me.countryCodeField
            End Get
            Set
                Me.countryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryName() As String
            Get
                Return Me.countryNameField
            End Get
            Set
                Me.countryNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class SubscriptionRequest
        
        Private webAuthenticationDetailField As WebAuthenticationDetail
        
        Private clientDetailField As ClientDetail
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private cspSolutionIdField As String
        
        Private cspTypeField As CspType
        
        Private cspTypeFieldSpecified As Boolean
        
        Private subscriberField As Party
        
        Private accountShippingAddressField As Address
        
        '''<remarks/>
        Public Property WebAuthenticationDetail() As WebAuthenticationDetail
            Get
                Return Me.webAuthenticationDetailField
            End Get
            Set
                Me.webAuthenticationDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientDetail() As ClientDetail
            Get
                Return Me.clientDetailField
            End Get
            Set
                Me.clientDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CspSolutionId() As String
            Get
                Return Me.cspSolutionIdField
            End Get
            Set
                Me.cspSolutionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CspType() As CspType
            Get
                Return Me.cspTypeField
            End Get
            Set
                Me.cspTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CspTypeSpecified() As Boolean
            Get
                Return Me.cspTypeFieldSpecified
            End Get
            Set
                Me.cspTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Subscriber() As Party
            Get
                Return Me.subscriberField
            End Get
            Set
                Me.subscriberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AccountShippingAddress() As Address
            Get
                Return Me.accountShippingAddressField
            End Get
            Set
                Me.accountShippingAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class ClientDetail
        
        Private accountNumberField As String
        
        Private meterNumberField As String
        
        Private integratorIdField As String
        
        Private regionField As ExpressRegionCode
        
        Private regionFieldSpecified As Boolean
        
        Private localizationField As Localization
        
        '''<remarks/>
        Public Property AccountNumber() As String
            Get
                Return Me.accountNumberField
            End Get
            Set
                Me.accountNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MeterNumber() As String
            Get
                Return Me.meterNumberField
            End Get
            Set
                Me.meterNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IntegratorId() As String
            Get
                Return Me.integratorIdField
            End Get
            Set
                Me.integratorIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Region() As ExpressRegionCode
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RegionSpecified() As Boolean
            Get
                Return Me.regionFieldSpecified
            End Get
            Set
                Me.regionFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Localization() As Localization
            Get
                Return Me.localizationField
            End Get
            Set
                Me.localizationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Public Enum ExpressRegionCode
        
        '''<remarks/>
        APAC
        
        '''<remarks/>
        CA
        
        '''<remarks/>
        EMEA
        
        '''<remarks/>
        LAC
        
        '''<remarks/>
        US
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Public Enum CspType
        
        '''<remarks/>
        CERTIFIED_SOLUTION_PROVIDER
        
        '''<remarks/>
        HTML_WEB_SERVICES_TOOL
        
        '''<remarks/>
        TRADITIONAL_API
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class VersionCaptureReply
        
        Private highestSeverityField As NotificationSeverityType
        
        Private highestSeverityFieldSpecified As Boolean
        
        Private notificationsField() As Notification
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        '''<remarks/>
        Public Property HighestSeverity() As NotificationSeverityType
            Get
                Return Me.highestSeverityField
            End Get
            Set
                Me.highestSeverityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HighestSeveritySpecified() As Boolean
            Get
                Return Me.highestSeverityFieldSpecified
            End Get
            Set
                Me.highestSeverityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Notifications")>  _
        Public Property Notifications() As Notification()
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class VersionCaptureRequest
        
        Private webAuthenticationDetailField As WebAuthenticationDetail
        
        Private clientDetailField As ClientDetail
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private originLocationIdField As String
        
        Private vendorProductPlatformField As String
        
        '''<remarks/>
        Public Property WebAuthenticationDetail() As WebAuthenticationDetail
            Get
                Return Me.webAuthenticationDetailField
            End Get
            Set
                Me.webAuthenticationDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientDetail() As ClientDetail
            Get
                Return Me.clientDetailField
            End Get
            Set
                Me.clientDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OriginLocationId() As String
            Get
                Return Me.originLocationIdField
            End Get
            Set
                Me.originLocationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VendorProductPlatform() As String
            Get
                Return Me.vendorProductPlatformField
            End Get
            Set
                Me.vendorProductPlatformField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class RegisterWebUserReply
        
        Private highestSeverityField As NotificationSeverityType
        
        Private highestSeverityFieldSpecified As Boolean
        
        Private notificationsField() As Notification
        
        Private transactionDetailField As TransactionDetail
        
        Private versionField As VersionId
        
        Private userCredentialField As WebAuthenticationCredential
        
        Private clientProductIdField As String
        
        '''<remarks/>
        Public Property HighestSeverity() As NotificationSeverityType
            Get
                Return Me.highestSeverityField
            End Get
            Set
                Me.highestSeverityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HighestSeveritySpecified() As Boolean
            Get
                Return Me.highestSeverityFieldSpecified
            End Get
            Set
                Me.highestSeverityFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Notifications")>  _
        Public Property Notifications() As Notification()
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TransactionDetail() As TransactionDetail
            Get
                Return Me.transactionDetailField
            End Get
            Set
                Me.transactionDetailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As VersionId
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserCredential() As WebAuthenticationCredential
            Get
                Return Me.userCredentialField
            End Get
            Set
                Me.userCredentialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientProductId() As String
            Get
                Return Me.clientProductIdField
            End Get
            Set
                Me.clientProductIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class ParsedPersonName
        
        Private prefixField As String
        
        Private titleField As String
        
        Private firstNameField As String
        
        Private middleNameField As String
        
        Private lastNameField As String
        
        Private suffixField As String
        
        '''<remarks/>
        Public Property Prefix() As String
            Get
                Return Me.prefixField
            End Get
            Set
                Me.prefixField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FirstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MiddleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Suffix() As String
            Get
                Return Me.suffixField
            End Get
            Set
                Me.suffixField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class ParsedContact
        
        Private personNameField As ParsedPersonName
        
        Private titleField As String
        
        Private companyNameField As String
        
        Private phoneNumberCountryCodeField As String
        
        Private phoneNumberAreaCodeField As String
        
        Private phoneNumberField As String
        
        Private phoneExtensionField As String
        
        Private pagerNumberField As String
        
        Private faxNumberField As String
        
        Private eMailAddressField As String
        
        '''<remarks/>
        Public Property PersonName() As ParsedPersonName
            Get
                Return Me.personNameField
            End Get
            Set
                Me.personNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyName() As String
            Get
                Return Me.companyNameField
            End Get
            Set
                Me.companyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumberCountryCode() As String
            Get
                Return Me.phoneNumberCountryCodeField
            End Get
            Set
                Me.phoneNumberCountryCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumberAreaCode() As String
            Get
                Return Me.phoneNumberAreaCodeField
            End Get
            Set
                Me.phoneNumberAreaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PhoneExtension() As String
            Get
                Return Me.phoneExtensionField
            End Get
            Set
                Me.phoneExtensionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PagerNumber() As String
            Get
                Return Me.pagerNumberField
            End Get
            Set
                Me.pagerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FaxNumber() As String
            Get
                Return Me.faxNumberField
            End Get
            Set
                Me.faxNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMailAddress() As String
            Get
                Return Me.eMailAddressField
            End Get
            Set
                Me.eMailAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Partial Public Class ParsedContactAndAddress
        
        Private contactField As ParsedContact
        
        Private addressField As Address
        
        '''<remarks/>
        Public Property Contact() As ParsedContact
            Get
                Return Me.contactField
            End Get
            Set
                Me.contactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://fedex.com/ws/registration/v7")>  _
    Public Enum WebServiceCategoryType
        
        '''<remarks/>
        OFFICE_AND_PRINT
        
        '''<remarks/>
        SHIPPING
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub registerWebUserCompletedEventHandler(ByVal sender As Object, ByVal e As registerWebUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class registerWebUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RegisterWebUserReply
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RegisterWebUserReply)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub versionCaptureCompletedEventHandler(ByVal sender As Object, ByVal e As versionCaptureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class versionCaptureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VersionCaptureReply
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VersionCaptureReply)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>  _
    Public Delegate Sub subscriptionCompletedEventHandler(ByVal sender As Object, ByVal e As subscriptionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class subscriptionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SubscriptionReply
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SubscriptionReply)
            End Get
        End Property
    End Class
End Namespace
